// Baramoji — MIT License
// Copyright (c) 2025 361do_sleep (original)
// Copyright (c) 2025 rebuildup and contributors (TypeScript port)
// Source: https://github.com/rebuildup/Ae_Baramoji_ts
//
// This file is auto-generated from src/entries/*.ts.
// Do not edit this file directly — modify the TypeScript source instead.

(function () {
    'use strict';

    // ExtendScript ES3 polyfills.
    //
    // ExtendScript's JavaScript engine is based on ES3 and is missing several
    // standard methods. Loading this file at the top of every entry guarantees
    // those methods exist before any user code runs.
    //
    // Rollup inlines this into every output .jsx, so the polyfills are baked in
    // without changing the runtime semantics of any later code.
    //
    // We use `any` here deliberately: TypeScript's lib knows about Array.prototype.indexOf etc.
    // (because it's an ES5 type), but ExtendScript's runtime doesn't have them.
    // The whole point of this file is to install them.
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // eslint-disable-next-line no-var
    var ArrayProto = Array.prototype;
    // eslint-disable-next-line no-var
    var StringProto = String.prototype;
    // Array.prototype.indexOf — ES5
    if (typeof ArrayProto.indexOf !== 'function') {
        ArrayProto.indexOf = function (searchElement, fromIndex) {
            var start = fromIndex || 0;
            var len = this.length;
            if (start < 0)
                start = Math.max(len + start, 0);
            for (var i = start; i < len; i++) {
                if (this[i] === searchElement)
                    return i;
            }
            return -1;
        };
    }
    // Array.prototype.forEach — ES5 (ExtendScript often ships this, but guard)
    if (typeof ArrayProto.forEach !== 'function') {
        ArrayProto.forEach = function (callback, thisArg) {
            for (var i = 0; i < this.length; i++) {
                callback.call(thisArg, this[i], i, this);
            }
        };
    }
    // Array.prototype.map — ES5
    if (typeof ArrayProto.map !== 'function') {
        ArrayProto.map = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                result.push(callback.call(thisArg, this[i], i, this));
            }
            return result;
        };
    }
    // Array.prototype.filter — ES5
    if (typeof ArrayProto.filter !== 'function') {
        ArrayProto.filter = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                if (callback.call(thisArg, this[i], i, this))
                    result.push(this[i]);
            }
            return result;
        };
    }
    // String.prototype.trim — ES5
    if (typeof StringProto.trim !== 'function') {
        StringProto.trim = function () {
            return this.replace(/^\s+|\s+$/g, '');
        };
    }
    // Object.keys — ES5
    if (typeof Object.keys !== 'function') {
        Object.keys = function (obj) {
            var keys = [];
            for (var k in obj) {
                if (Object.prototype.hasOwnProperty.call(obj, k))
                    keys.push(k);
            }
            return keys;
        };
    }
    // Note: src/types/*.d.ts are picked up by tsconfig include, so no runtime
    // import is needed (and .d.ts files don't generate runtime code anyway).

    // Shared constants for the Baramoji decomposition algorithms.
    /** AE internal menu command that converts the selected TextLayer into ShapeLayers. */
    var CMD_CREATE_TEXT_SHAPE = 3781;
    // ADBE match names (stable across AE versions; "matchName" / "matchNames").
    var ADBE = {
        TransformGroup: 'ADBE Transform Group',
        Position: 'ADBE Position',
        Position_0: 'ADBE Position_0',
        Position_1: 'ADBE Position_1',
        Position_2: 'ADBE Position_2',
        AnchorPoint: 'ADBE Anchor Point',
        Scale: 'ADBE Scale',
        RotateZ: 'ADBE Rotate Z',
        XRotation: 'ADBE X Rotation',
        YRotation: 'ADBE Y Rotation',
        ZRotation: 'ADBE Z Rotation',
        Orientation: 'ADBE Orientation',
        RootVectorsGroup: 'ADBE Root Vectors Group',
        VectorGroup: 'ADBE Vector Group',
        VectorMaterialsGroup: 'ADBE Vector Materials Group',
        VectorShapeGroup: 'ADBE Vector Shape - Group',
        VectorFilterMerge: 'ADBE Vector Filter - Merge',
        VectorAnchor: 'ADBE Vector Anchor',
        Contents: 'Contents',
        SourceText: 'Source Text',
        EffectParade: 'ADBE Effect Parade',
        PEDG: 'PEDG',
        PEDG2: 'PEDG2'
    };
    // Undo group names — used for AE's undo system.
    var UNDO = {
        DecomposeTextToText: 'DecomposeTextLayers',
        DecomposeTextToShape: 'DecomposeTextToShapeLayers',
        DecomposeTextToParts: 'Text to Parts Decompose'
    };
    // Default alert / dialog text.
    var ALERT = {
        NoCompositionText: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionShape: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionParts: 'No composition is active. Please open a composition and select text layers or shape layers.',
        NoLayersText: 'No layers selected. Please select one or more text layers.',
        NoLayersShape: 'No layers selected. Please select one or more text layers.',
        NoLayersParts: 'No layers selected. Please select one or more text layers or shape layers.',
        FailedShapesFromText: 'Failed to create shapes from text for layer: ',
        FailedShapesFromTextA: 'Failed to create shapes from text for a layer.',
        FailedShapesNoVector: 'Selected layer does not contain vector content: ',
        NoValidForParts: 'No valid text layers or shape layers found in selection. Please select layers with vector content.',
        RemoveDeepGlow: 'Please temporarily remove the Deep Glow effect from the layer: '
    };

    // Property helpers for capturing and applying layer state.
    //
    // Used by both text decomposition (per-character style extraction) and parts
    // decomposition (preserve original layer attributes when duplicating).
    /**
     * Capture the subset of layer properties that the Baramoji algorithms
     * preserve when duplicating / moving / re-creating layers.
     */
    function captureBasicProperties(layer) {
        var props = {};
        try {
            props.name = layer.name;
            props.inPoint = layer.inPoint;
            props.outPoint = layer.outPoint;
            props.enabled = layer.enabled;
            props.solo = layer.solo;
            props.shy = layer.shy;
            props.locked = layer.locked;
            props.label = layer.label;
            props.comment = layer.comment;
            props.threeDLayer = layer.threeDLayer;
            props.parent = layer.parent;
            props.blendingMode = layer.blendingMode;
        }
        catch (e) {
        }
        return props;
    }
    /** Apply a previously captured property set to a layer. */
    function applyBasicProperties(layer, props) {
        try {
            layer.inPoint = props.inPoint;
            layer.outPoint = props.outPoint;
            layer.enabled = props.enabled;
            layer.solo = props.solo;
            layer.shy = props.shy;
            layer.locked = props.locked;
            layer.comment = props.comment;
            layer.threeDLayer = props.threeDLayer;
            layer.blendingMode = props.blendingMode;
            if (props.parent) {
                try {
                    layer.parent = props.parent;
                }
                catch (e) {
                    void e;
                }
            }
        }
        catch (e) {
        }
    }

    // adjustAnchorPoint — the anchor/position math that appears in both
    // Baramoji_shape.jsx (inline) and Baramoji_part.jsx (extracted as
    // `adjustAnchorPoint`). The `_part` version accepts a `pet` parameter to
    // control where the vector anchor is set; we preserve that here.
    /**
     * Move a layer's anchor point to the visual center of its sourceRect and
     * apply the inverse translation to its position so the layer visually
     * stays in place. No-op if the transform group has keyframes.
     *
     * @param pet 0 = transform-group anchor; 1 = root vectors group anchor;
     *            2 = nested (1).property(2).property(1) anchor (used in parts).
     */
    function adjustAnchorPoint(layer, pet) {
        var laytrans = layer.property(ADBE.TransformGroup);
        if (!laytrans)
            return;
        // Skip if any of these are animated.
        if (laytrans.property(ADBE.Position).numKeys !== 0 ||
            laytrans.property(ADBE.Position_0).numKeys !== 0 ||
            laytrans.property(ADBE.Position_1).numKeys !== 0 ||
            laytrans.property(ADBE.AnchorPoint).numKeys !== 0) {
            return;
        }
        try {
            var RZ = laytrans.property(ADBE.RotateZ).value;
            var sourceRect = layer.sourceRectAtTime(0, true);
            var CX = sourceRect.width * 0.5 + sourceRect.left;
            var CY = sourceRect.height * 0.5 + sourceRect.top;
            var scale = laytrans.property(ADBE.Scale).value;
            var SX = scale[0];
            var SY = scale[1];
            var anchor = laytrans.property(ADBE.AnchorPoint).value;
            var APX = anchor[0];
            var APY = anchor[1];
            var PX = 0;
            var PY = 0;
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                var pos = laytrans.property(ADBE.Position).value;
                PX = pos[0];
                PY = pos[1];
            }
            else {
                PX = laytrans.property(ADBE.Position_0).value;
                PY = laytrans.property(ADBE.Position_1).value;
            }
            laytrans.property(ADBE.AnchorPoint).setValue([0, 0, 0]);
            if (pet === 1) ;
            else if (pet === 2) {
                layer
                    .property(ADBE.RootVectorsGroup)
                    .property(1)
                    .property(2)
                    .property(1)
                    .property(3)
                    .property('ADBE Vector Anchor').setValue([CX, CY]);
            }
            else ;
            var DX = (CX - APX) * 0.01 * SX;
            var DY = (CY - APY) * 0.01 * SY;
            var rotRad = (RZ * Math.PI) / 180;
            var newX = PX + DX * Math.cos(rotRad) - DY * Math.sin(rotRad);
            var newY = PY + DX * Math.sin(rotRad) + DY * Math.cos(rotRad);
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                laytrans.property(ADBE.Position).setValue([newX, newY, 0]);
            }
            else {
                laytrans.property(ADBE.Position_0).setValue(newX);
                laytrans.property(ADBE.Position_1).setValue(newY);
            }
        }
        catch (e) {
        }
    }

    // Heuristics for detecting and removing artifacts left in a comp by a
    // previous run of the decomposition algorithms.
    //
    // Each algorithm leaves layers with distinctive names. We use those names as
    // a best-effort signal of "this comp already has a decomposition". Users who
    // happen to have unrelated layers with matching names can pre-select to
    // avoid false positives.
    //
    // Algorithm → naming convention:
    //   - text decomposition: per-character TextLayer whose name is the single
    //     character (possibly filtered through the same charFilter the algorithm
    //     applies). See `nameTextArtifact`.
    //   - shape decomposition: per-character ShapeLayer named "char_<char>".
    //     See `nameShapeArtifact`.
    //   - parts decomposition: per-part ShapeLayer named "<partName> Outline ".
    //     See `namePartsArtifact`.
    /**
     * Return true if `sourceLayer` looks like it already has been decomposed
     * inside `comp` by `algorithm`. The check is best-effort and only inspects
     * siblings within the same comp.
     */
    function hasDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return false;
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer))
                return true;
        }
        return false;
    }
    /**
     * Remove any layer in `comp` (other than `sourceLayer` itself) that looks
     * like an artifact of a previous `algorithm` run. Returns the count of
     * removed layers. Detection is the same heuristic as `hasDecompositionArtifacts`.
     */
    function removeDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return 0;
        // Collect matching layers first; removing while iterating mutates indices.
        var toRemove = [];
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer))
                toRemove.push(layer);
        }
        for (var _i = 0, toRemove_1 = toRemove; _i < toRemove_1.length; _i++) {
            var layer = toRemove_1[_i];
            try {
                layer.remove();
            }
            catch (e) {
            }
        }
        return toRemove.length;
    }
    function matchesArtifact(layer, sourceLayer, algorithm) {
        if (!layer || !layer.name)
            return false;
        var name = String(layer.name);
        {
            // Parts decomposition leaves shape layers named "<partName> Outline ".
            if (name.length < 10)
                return false;
            if (name.indexOf(' Outline ') < 0)
                return false;
            return isShapeOrVectorLayer(layer);
        }
    }
    function isShapeOrVectorLayer(layer) {
        try {
            if (layer instanceof globalThis.ShapeLayer)
                return true;
        }
        catch (e) {
        }
        try {
            return layer.property(ADBE.RootVectorsGroup) !== null;
        }
        catch (e) {
            return false;
        }
    }

    // Decompose a TextLayer (or ShapeLayer with vector content) into per-part
    // shape layers using path signed-area + point-in-polygon merge logic.
    //
    // This is the algorithm that powers:
    //   - Baramoji_part.jsx
    //   - Baramoji_part_win.jsx
    //   - the "Parts" button in Baramoji.jsx
    //
    // The algorithm is verbatim from the original .jsx (Copyright 2025 361do_sleep)
    // with type annotations added and shared helpers factored into `properties.ts` /
    // `anchor.ts`. Logic MUST stay byte-identical so the result matches the legacy
    // output.
    function runDecomposeTextToShapeParts(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress, _e = opts.duplicateMode, duplicateMode = _e === void 0 ? 'skip' : _e;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToParts);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionParts);
                app.endUndoGroup();
                return;
            }
            var selectedLayers = comp.selectedLayers;
            if (selectedLayers.length === 0) {
                alert(ALERT.NoLayersParts);
                app.endUndoGroup();
                return;
            }
            if (duplicateMode === 'cancel') {
                for (var i = 0; i < selectedLayers.length; i++) {
                    if (hasDecompositionArtifacts(comp, selectedLayers[i], 'parts')) {
                        alert('Aborted: a selected layer already has a parts decomposition. ' +
                            'Re-run with Skip or Overwrite to change existing layers.');
                        app.endUndoGroup();
                        return;
                    }
                }
            }
            try {
                var textLayerIndices = [];
                var layerProperties = [];
                for (var i = 0; i < selectedLayers.length; i++) {
                    var layer = selectedLayers[i];
                    var isTextLayer = layer instanceof globalThis.TextLayer;
                    var isShapeLayer = layer instanceof globalThis.AVLayer || layer.constructor.name === 'ShapeLayer';
                    var hasVectorGroup = false;
                    try {
                        hasVectorGroup = layer.property(ADBE.RootVectorsGroup) !== null;
                    }
                    catch (e) {
                        hasVectorGroup = false;
                    }
                    if (isTextLayer || (isShapeLayer && hasVectorGroup)) {
                        textLayerIndices.push(layer.index);
                        layerProperties.push(captureBasicProperties(layer));
                    }
                    layer.selected = false;
                }
                textLayerIndices.sort(function (a, b) { return a - b; });
                if (textLayerIndices.length === 0) {
                    alert(ALERT.NoValidForParts);
                    app.endUndoGroup();
                    return;
                }
                var totalSteps = Math.max(1, textLayerIndices.length);
                for (var i = 0; i < textLayerIndices.length; i++) {
                    var layerIndex = textLayerIndices[i];
                    var originalProps = layerProperties[i];
                    onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.round((i / totalSteps) * 80), 'Processing layer ' + (i + 1) + '/' + totalSteps + '...');
                    var currentLayer = comp.layers[layerIndex];
                    currentLayer.selected = true;
                    if (duplicateMode === 'skip' && hasDecompositionArtifacts(comp, currentLayer, 'parts')) {
                        onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.round((i / totalSteps) * 80), 'Skipping already-decomposed layer: ' + currentLayer.name);
                        currentLayer.selected = false;
                        continue;
                    }
                    if (duplicateMode === 'overwrite') {
                        var removed = removeDecompositionArtifacts(comp, currentLayer, 'parts');
                        if (removed > 0)
                            onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.round((i / totalSteps) * 80), 'Removed ' + removed + ' stale layer(s) for: ' + currentLayer.name);
                    }
                    var baseShapeLayer = void 0;
                    if (currentLayer instanceof globalThis.TextLayer) {
                        app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                        baseShapeLayer =
                            comp.selectedLayers && comp.selectedLayers.length > 0
                                ? comp.selectedLayers[0]
                                : null;
                        if (!baseShapeLayer) {
                            alert(ALERT.FailedShapesFromTextA);
                            currentLayer.selected = false;
                            continue;
                        }
                    }
                    else {
                        try {
                            if (!currentLayer.property(ADBE.RootVectorsGroup)) {
                                alert(ALERT.FailedShapesNoVector + currentLayer.name);
                                currentLayer.selected = false;
                                continue;
                            }
                            baseShapeLayer = currentLayer;
                        }
                        catch (e) {
                            alert('Error processing shape layer: ' + e.toString());
                            currentLayer.selected = false;
                            continue;
                        }
                    }
                    var shapeLabel = undefined;
                    try {
                        shapeLabel = baseShapeLayer.label;
                    }
                    catch (e) {
                        void e;
                    }
                    processPartsMerge(baseShapeLayer);
                    var keepOriginal = currentLayer.constructor.name === 'ShapeLayer';
                    var resultLayers = processPartsDecompose(baseShapeLayer, originalProps, shapeLabel, keepOriginal);
                    if (resultLayers && resultLayers.length > 0) {
                        try {
                            for (var s = 0; s < comp.selectedLayers.length; s++) {
                                comp.selectedLayers[s].selected = false;
                            }
                            for (var r = 0; r < resultLayers.length; r++) {
                                resultLayers[r].selected = true;
                            }
                        }
                        catch (e) {
                            void e;
                        }
                    }
                }
            }
            catch (error) {
                alert('Error occurred: ' + error.toString());
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(95, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }
    /**
     * Merge overlapping paths inside the shape layer's "ADBE Root Vectors Group"
     * using signed-area + point-in-polygon tests. Identical to the original
     * Baramoji_part.jsx implementation.
     */
    function processPartsMerge(layer) {
        var vectorGroup = layer.property(ADBE.RootVectorsGroup);
        var prowloop = 1;
        while (prowloop <= vectorGroup.numProperties) {
            var pathcount = 1;
            var pathnum = 3;
            var nowtext = vectorGroup.property(prowloop).property(2);
            if (nowtext.numProperties === 3) {
                pathnum--;
            }
            var area = [];
            var maxarea = 0;
            var mavec = true;
            var pathveccheckloop = 1;
            var areavecchash = [];
            var pathnowloop = 0;
            while (pathveccheckloop <= nowtext.numProperties - pathnum) {
                var nexdex = 0;
                var areachash = 0;
                var nowpath = nowtext.property(pathveccheckloop).property(2);
                var nowpathpoint = nowpath.value.vertices;
                for (var i = 0; i < nowpathpoint.length; i++) {
                    nexdex = (i + 1) % nowpathpoint.length;
                    areachash += nowpathpoint[i][0] * nowpathpoint[nexdex][1];
                    areachash -= nowpathpoint[nexdex][0] * nowpathpoint[i][1];
                }
                if (Math.abs(areachash) > Math.abs(maxarea)) {
                    maxarea = areachash;
                }
                areavecchash[pathveccheckloop - 1] = areachash;
                pathveccheckloop++;
            }
            if (maxarea > 0) {
                mavec = false;
            }
            while (pathcount <= nowtext.numProperties - pathnum) {
                area[pathcount - 1] = areavecchash[pathnowloop];
                if ((area[pathcount - 1] < 0) === mavec) {
                    var countloop = 1;
                    var areamove = false;
                    nowtext.addProperty(ADBE.VectorGroup).moveTo(pathcount);
                    nowtext.property(pathcount).property(ADBE.VectorMaterialsGroup).remove();
                    nowtext.property(pathcount).name = nowtext.property(pathcount + 1).name;
                    nowtext.property(pathcount).property(2).addProperty(ADBE.VectorShapeGroup);
                    nowtext
                        .property(pathcount)
                        .property(2)
                        .property(1)
                        .property(2)
                        .setValue(nowtext.property(pathcount + 1).property(2).value);
                    nowtext.property(pathcount).property(2).property(1).name = nowtext.property(pathcount + 1).name;
                    nowtext.property(pathcount + 1).remove();
                    while (countloop < pathcount) {
                        if (area[countloop - 1] < area[pathcount - 1]) {
                            nowtext.property(pathcount).moveTo(countloop);
                            area.splice(countloop - 1, 0, area[pathcount - 1]);
                            areamove = true;
                        }
                        countloop++;
                    }
                    if (!areamove) {
                        nowtext.property(pathcount).moveTo(countloop);
                    }
                    pathcount++;
                }
                else {
                    nowtext.property(pathcount).moveTo(nowtext.numProperties - 3);
                    pathnum++;
                }
                pathnowloop++;
            }
            var countloop2 = 1;
            while (countloop2 < pathcount) {
                var contentsloop = 0;
                var Mflag = false;
                while (contentsloop < nowtext.numProperties - (pathcount + 2)) {
                    var ppflag = false;
                    var checkpoint = [
                        nowtext.property(pathcount + contentsloop).property(2).value.vertices[0][0],
                        nowtext.property(pathcount + contentsloop).property(2).value.vertices[0][1],
                    ];
                    var cn = 0;
                    var nowtexpath = nowtext
                        .property(countloop2)
                        .property(2)
                        .property(1)
                        .property(2);
                    var nowpathpoint = nowtexpath.value.vertices;
                    var nowpathoutT = nowtexpath.value.outTangents;
                    var nowpathinT = nowtexpath.value.inTangents;
                    var bezposX = [];
                    var bezposY = [];
                    for (var k = 0; k < nowpathpoint.length; k++) {
                        var beznexdex = (k + 1) % nowpathpoint.length;
                        var bez3 = 0.125;
                        var p0 = [nowpathpoint[k][0], nowpathpoint[k][1]];
                        var p1 = [
                            nowpathpoint[k][0] + nowpathoutT[k][0],
                            nowpathpoint[k][1] + nowpathoutT[k][1],
                        ];
                        var p2 = [
                            nowpathpoint[beznexdex][0] + nowpathinT[beznexdex][0],
                            nowpathpoint[beznexdex][1] + nowpathinT[beznexdex][1],
                        ];
                        var p3 = [nowpathpoint[beznexdex][0], nowpathpoint[beznexdex][1]];
                        bezposX[k] = bez3 * p0[0] + 3 * bez3 * p1[0] + 3 * bez3 * p2[0] + bez3 * p3[0];
                        bezposY[k] = bez3 * p0[1] + 3 * bez3 * p1[1] + 3 * bez3 * p2[1] + bez3 * p3[1];
                    }
                    var u = 0;
                    var bppointpos = [];
                    for (var j = 0; j < nowpathpoint.length * 2; j++) {
                        if (j % 2 === 0) {
                            bppointpos[j] = nowpathpoint[u];
                        }
                        else {
                            bppointpos[j] = [bezposX[u], bezposY[u]];
                            u++;
                        }
                    }
                    for (var i = 0; i < bppointpos.length; i++) {
                        var nexdex = (i + 1) % bppointpos.length;
                        if ((bppointpos[i][1] <= checkpoint[1] && bppointpos[nexdex][1] > checkpoint[1]) ||
                            (bppointpos[i][1] > checkpoint[1] && bppointpos[nexdex][1] <= checkpoint[1])) {
                            var vt = (checkpoint[1] - bppointpos[i][1]) / (bppointpos[nexdex][1] - bppointpos[i][1]);
                            if (checkpoint[0] <
                                bppointpos[i][0] + vt * (bppointpos[nexdex][0] - bppointpos[i][0])) {
                                cn++;
                            }
                        }
                    }
                    ppflag = cn % 2 !== 0;
                    if (ppflag) {
                        nowtext.property(countloop2).property(2).addProperty(ADBE.VectorShapeGroup).moveTo(2);
                        nowtext
                            .property(countloop2)
                            .property(2)
                            .property(2)
                            .property(2)
                            .setValue(nowtext.property(pathcount + contentsloop).property(2).value);
                        nowtext.property(countloop2).property(2).property(2).name =
                            nowtext.property(pathcount + contentsloop).name;
                        nowtext.property(pathcount + contentsloop).remove();
                        contentsloop--;
                        if (!Mflag) {
                            nowtext.property(countloop2).property(2).addProperty(ADBE.VectorFilterMerge);
                            Mflag = true;
                        }
                    }
                    contentsloop++;
                }
                countloop2++;
            }
            prowloop++;
        }
    }
    /**
     * Produce one duplicated layer per character outline from the merged
     * vector group.
     */
    function processPartsDecompose(layer, originalProps, targetLabel, keepOriginal) {
        var vectorGroup = layer.property(ADBE.RootVectorsGroup);
        var proloop = 0;
        var texnum = vectorGroup.numProperties;
        var resultLayers = [];
        while (proloop < texnum) {
            var character = vectorGroup.property(1);
            var contents = character.property(2);
            var pronum = contents.numProperties - 3;
            var prowloop = 1;
            while (prowloop < pronum) {
                var duplicatedLayer = layer.duplicate();
                duplicatedLayer.name = character.name + ' Outline ';
                var dupContents = duplicatedLayer
                    .property(ADBE.RootVectorsGroup)
                    .property(1)
                    .property(2);
                while (dupContents.numProperties > 4) {
                    dupContents.property(2).remove();
                }
                if (dupContents.property(2).matchName === ADBE.VectorFilterMerge) {
                    dupContents.property(2).remove();
                }
                contents.property(1).remove();
                while (duplicatedLayer.property(ADBE.RootVectorsGroup).numProperties > 1) {
                    duplicatedLayer.property(ADBE.RootVectorsGroup).property(2).remove();
                }
                adjustAnchorPoint(duplicatedLayer, 2);
                applyBasicProperties(duplicatedLayer, originalProps);
                if (typeof targetLabel !== 'undefined') {
                    try {
                        duplicatedLayer.label = targetLabel;
                    }
                    catch (e) {
                    }
                }
                try {
                    if (resultLayers.length === 0) {
                        duplicatedLayer.moveBefore(layer);
                    }
                    else {
                        var lastLayer = resultLayers[resultLayers.length - 1];
                        duplicatedLayer.moveBefore(lastLayer);
                    }
                }
                catch (e) {
                }
                resultLayers.push(duplicatedLayer);
                prowloop++;
            }
            var finalLayer = layer.duplicate();
            finalLayer.name = character.name + ' Outline ';
            var finalContents = finalLayer
                .property(ADBE.RootVectorsGroup)
                .property(1)
                .property(2);
            if (finalContents.property(2).matchName === ADBE.VectorFilterMerge) {
                finalContents.property(2).remove();
            }
            while (finalLayer.property(ADBE.RootVectorsGroup).numProperties > 1) {
                finalLayer.property(ADBE.RootVectorsGroup).property(2).remove();
            }
            adjustAnchorPoint(finalLayer, 2);
            applyBasicProperties(finalLayer, originalProps);
            if (typeof targetLabel !== 'undefined') {
                try {
                    finalLayer.label = targetLabel;
                }
                catch (e) {
                }
            }
            try {
                if (resultLayers.length === 0) {
                    finalLayer.moveBefore(layer);
                }
                else {
                    var lastLayer = resultLayers[resultLayers.length - 1];
                    finalLayer.moveBefore(lastLayer);
                }
            }
            catch (e) {
            }
            resultLayers.push(finalLayer);
            vectorGroup.property(1).remove();
            proloop++;
        }
        if (keepOriginal) {
            try {
                layer.enabled = false;
            }
            catch (e) {
            }
        }
        else {
            try {
                layer.remove();
            }
            catch (e) {
            }
        }
        return resultLayers;
    }

    // Baramoji_part.jsx entry — text/shape-layer → part-based shape decomposition.
    // Original: Baramoji_part.jsx (Copyright 2025 361do_sleep).
    (function BaramojiPartEntry() {
        runDecomposeTextToShapeParts();
    })();

})();
