// Baramoji — MIT License
// Copyright (c) 2025 361do_sleep (original)
// Copyright (c) 2025 rebuildup and contributors (TypeScript port)
// Source: https://github.com/rebuildup/Ae_Baramoji_ts
//
// This file is auto-generated from src/entries/*.ts.
// Do not edit this file directly — modify the TypeScript source instead.

(function () {
    'use strict';

    // ExtendScript ES3 polyfills.
    //
    // ExtendScript's JavaScript engine is based on ES3 and is missing several
    // standard methods. Loading this file at the top of every entry guarantees
    // those methods exist before any user code runs.
    //
    // Rollup inlines this into every output .jsx, so the polyfills are baked in
    // without changing the runtime semantics of any later code.
    //
    // We use `any` here deliberately: TypeScript's lib knows about Array.prototype.indexOf etc.
    // (because it's an ES5 type), but ExtendScript's runtime doesn't have them.
    // The whole point of this file is to install them.
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // eslint-disable-next-line no-var
    var ArrayProto = Array.prototype;
    // eslint-disable-next-line no-var
    var StringProto = String.prototype;
    // Array.prototype.indexOf — ES5
    if (typeof ArrayProto.indexOf !== 'function') {
        ArrayProto.indexOf = function (searchElement, fromIndex) {
            var start = fromIndex || 0;
            var len = this.length;
            if (start < 0)
                start = Math.max(len + start, 0);
            for (var i = start; i < len; i++) {
                if (this[i] === searchElement)
                    return i;
            }
            return -1;
        };
    }
    // Array.prototype.forEach — ES5 (ExtendScript often ships this, but guard)
    if (typeof ArrayProto.forEach !== 'function') {
        ArrayProto.forEach = function (callback, thisArg) {
            for (var i = 0; i < this.length; i++) {
                callback.call(thisArg, this[i], i, this);
            }
        };
    }
    // Array.prototype.map — ES5
    if (typeof ArrayProto.map !== 'function') {
        ArrayProto.map = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                result.push(callback.call(thisArg, this[i], i, this));
            }
            return result;
        };
    }
    // Array.prototype.filter — ES5
    if (typeof ArrayProto.filter !== 'function') {
        ArrayProto.filter = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                if (callback.call(thisArg, this[i], i, this))
                    result.push(this[i]);
            }
            return result;
        };
    }
    // String.prototype.trim — ES5
    if (typeof StringProto.trim !== 'function') {
        StringProto.trim = function () {
            return this.replace(/^\s+|\s+$/g, '');
        };
    }
    // Object.keys — ES5
    if (typeof Object.keys !== 'function') {
        Object.keys = function (obj) {
            var keys = [];
            for (var k in obj) {
                if (Object.prototype.hasOwnProperty.call(obj, k))
                    keys.push(k);
            }
            return keys;
        };
    }
    // Note: src/types/*.d.ts are picked up by tsconfig include, so no runtime
    // import is needed (and .d.ts files don't generate runtime code anyway).

    // Shared constants for the Baramoji decomposition algorithms.
    /** AE internal menu command that converts the selected TextLayer into ShapeLayers. */
    var CMD_CREATE_TEXT_SHAPE = 3781;
    // ADBE match names (stable across AE versions; "matchName" / "matchNames").
    var ADBE = {
        TransformGroup: 'ADBE Transform Group',
        Position: 'ADBE Position',
        Position_0: 'ADBE Position_0',
        Position_1: 'ADBE Position_1',
        Position_2: 'ADBE Position_2',
        AnchorPoint: 'ADBE Anchor Point',
        Scale: 'ADBE Scale',
        RotateZ: 'ADBE Rotate Z',
        XRotation: 'ADBE X Rotation',
        YRotation: 'ADBE Y Rotation',
        ZRotation: 'ADBE Z Rotation',
        Orientation: 'ADBE Orientation',
        RootVectorsGroup: 'ADBE Root Vectors Group',
        VectorGroup: 'ADBE Vector Group',
        VectorMaterialsGroup: 'ADBE Vector Materials Group',
        VectorShapeGroup: 'ADBE Vector Shape - Group',
        VectorFilterMerge: 'ADBE Vector Filter - Merge',
        VectorAnchor: 'ADBE Vector Anchor',
        Contents: 'Contents',
        SourceText: 'Source Text',
        EffectParade: 'ADBE Effect Parade',
        PEDG: 'PEDG',
        PEDG2: 'PEDG2'
    };
    // Undo group names — used for AE's undo system.
    var UNDO = {
        DecomposeTextToText: 'DecomposeTextLayers',
        DecomposeTextToShape: 'DecomposeTextToShapeLayers',
        DecomposeTextToParts: 'Text to Parts Decompose'
    };
    // Default alert / dialog text.
    var ALERT = {
        NoCompositionText: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionShape: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionParts: 'No composition is active. Please open a composition and select text layers or shape layers.',
        NoLayersText: 'No layers selected. Please select one or more text layers.',
        NoLayersShape: 'No layers selected. Please select one or more text layers.',
        NoLayersParts: 'No layers selected. Please select one or more text layers or shape layers.',
        FailedShapesFromText: 'Failed to create shapes from text for layer: ',
        FailedShapesFromTextA: 'Failed to create shapes from text for a layer.',
        FailedShapesNoVector: 'Selected layer does not contain vector content: ',
        NoValidForParts: 'No valid text layers or shape layers found in selection. Please select layers with vector content.',
        RemoveDeepGlow: 'Please temporarily remove the Deep Glow effect from the layer: '
    };

    // Build the ScriptUI palette shown by Baramoji.jsx (the unified entry).
    //
    // Three buttons — Texts, Shapes, Parts — each wired to one of the three
    // decomposition algorithms via the onProgress stub passed by the entry file.
    function buildPalette(cb) {
        // ExtendScript's Window is a global constructor. We access via any to avoid
        // the strict signature mismatch.
        var Win = globalThis.Window;
        var win = new Win('palette', 'Baramoji', undefined);
        win.layout = { layout: true };
        var colGroup = win.add('group');
        colGroup.orientation = 'column';
        var btnTexts = colGroup.add('button', undefined, 'Texts');
        btnTexts.onClick = cb.onTexts;
        var btnShapes = colGroup.add('button', undefined, 'Shapes');
        btnShapes.onClick = cb.onShapes;
        var btnParts = colGroup.add('button', undefined, 'Parts');
        btnParts.onClick = cb.onParts;
        return win;
    }

    // Property helpers for capturing and applying layer state.
    //
    // Used by both text decomposition (per-character style extraction) and parts
    // decomposition (preserve original layer attributes when duplicating).
    /**
     * Capture the subset of layer properties that the Baramoji algorithms
     * preserve when duplicating / moving / re-creating layers.
     */
    function captureBasicProperties(layer) {
        var props = {};
        try {
            props.name = layer.name;
            props.inPoint = layer.inPoint;
            props.outPoint = layer.outPoint;
            props.enabled = layer.enabled;
            props.solo = layer.solo;
            props.shy = layer.shy;
            props.locked = layer.locked;
            props.label = layer.label;
            props.comment = layer.comment;
            props.threeDLayer = layer.threeDLayer;
            props.parent = layer.parent;
            props.blendingMode = layer.blendingMode;
        }
        catch (e) {
        }
        return props;
    }
    /** Apply a previously captured property set to a layer. */
    function applyBasicProperties(layer, props) {
        try {
            layer.inPoint = props.inPoint;
            layer.outPoint = props.outPoint;
            layer.enabled = props.enabled;
            layer.solo = props.solo;
            layer.shy = props.shy;
            layer.locked = props.locked;
            layer.comment = props.comment;
            layer.threeDLayer = props.threeDLayer;
            layer.blendingMode = props.blendingMode;
            if (props.parent) {
                try {
                    layer.parent = props.parent;
                }
                catch (e) {
                    void e;
                }
            }
        }
        catch (e) {
        }
    }
    /** Set a property's value, falling back silently on animated properties. */
    function setPosition(prop, value) {
        if (!prop)
            return;
        if (prop.numKeys === 0) {
            prop.setValue(value);
        }
        else {
            try {
                prop.setValue(value);
            }
            catch (e) {
            }
        }
    }
    /**
     * Extract an array-valued TextLayer style attribute as a comma-separated
     * string by temporarily setting an expression. Original Baramoji_txt.jsx
     * uses this trick to read fontSize / fillColor / etc. per character.
     */
    function getPropertyArray(property, layer) {
        var txtSave = layer.property(ADBE.SourceText).value;
        var expression = 'var output_txt=[]; for(var i=0;i<text.sourceText.length;i++){output_txt.push(text.sourceText.getStyleAt(i).' +
            property +
            ');}output_txt;';
        layer.property(ADBE.SourceText).expression = expression;
        var output = layer.property(ADBE.SourceText).value;
        layer.property(ADBE.SourceText).expression = '';
        // Restore the original TextDocument (assigning to .value triggers setValue).
        layer.text.sourceText.setValue(txtSave);
        return String(output);
    }
    /** Get the source rect (size) of a layer at the comp's current time. */
    function getLayerSize(layer) {
        var comp = app.project.activeItem;
        var bounds = layer.sourceRectAtTime(comp.time, false);
        return [bounds.width, bounds.height];
    }
    /** Detect "Deep Glow" effect (the popular plugin) on a layer. */
    function hasDeepGlow(layer) {
        try {
            var ef = layer.property(ADBE.EffectParade);
            if (!ef)
                return false;
            if (ef.property(ADBE.PEDG) || ef.property(ADBE.PEDG2))
                return true;
        }
        catch (e) {
        }
        return false;
    }

    // 3D rotation math used by the text decomposition algorithm.
    //
    // AE text layers can be 3D, so positioning each decomposed character layer
    // requires composing rotation matrices. The original Baramoji_txt.jsx
    // inlines these helpers; we extract them here for sharing with other
    // entries.
    function degToRad(deg) {
        return (deg * Math.PI) / 180;
    }
    /**
     * Convert a 3D rotation vector (degrees) into a rotation matrix.
     * Standard Euler-angle convention: rot = [xDeg, yDeg, zDeg].
     */
    function rotationToMatrix(rot) {
        var rx = degToRad(rot[0]);
        var ry = degToRad(rot[1]);
        var rz = degToRad(rot[2]);
        var cosX = Math.cos(rx);
        var sinX = Math.sin(rx);
        var cosY = Math.cos(ry);
        var sinY = Math.sin(ry);
        var cosZ = Math.cos(rz);
        var sinZ = Math.sin(rz);
        return [
            [cosY * cosZ, -cosY * sinZ, sinY],
            [sinX * sinY * cosZ + cosX * sinZ, -sinX * sinY * sinZ + cosX * cosZ, -sinX * cosY],
            [-cosX * sinY * cosZ + sinX * sinZ, cosX * sinY * sinZ + sinX * cosZ, cosX * cosY],
        ];
    }
    function multiplyMatrix3x3(a, b) {
        var r = [
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
        ];
        for (var i = 0; i < 3; i++) {
            for (var j = 0; j < 3; j++) {
                r[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
            }
        }
        return r;
    }
    function applyMatrixToOffset(matrix, x, y, z) {
        return [
            x * matrix[0][0] + y * matrix[0][1] + z * matrix[0][2],
            x * matrix[1][0] + y * matrix[1][1] + z * matrix[1][2],
            x * matrix[2][0] + y * matrix[2][1] + z * matrix[2][2],
        ];
    }

    // adjustAnchorPoint — the anchor/position math that appears in both
    // Baramoji_shape.jsx (inline) and Baramoji_part.jsx (extracted as
    // `adjustAnchorPoint`). The `_part` version accepts a `pet` parameter to
    // control where the vector anchor is set; we preserve that here.
    /**
     * Move a layer's anchor point to the visual center of its sourceRect and
     * apply the inverse translation to its position so the layer visually
     * stays in place. No-op if the transform group has keyframes.
     *
     * @param pet 0 = transform-group anchor; 1 = root vectors group anchor;
     *            2 = nested (1).property(2).property(1) anchor (used in parts).
     */
    function adjustAnchorPoint(layer, pet) {
        var laytrans = layer.property(ADBE.TransformGroup);
        if (!laytrans)
            return;
        // Skip if any of these are animated.
        if (laytrans.property(ADBE.Position).numKeys !== 0 ||
            laytrans.property(ADBE.Position_0).numKeys !== 0 ||
            laytrans.property(ADBE.Position_1).numKeys !== 0 ||
            laytrans.property(ADBE.AnchorPoint).numKeys !== 0) {
            return;
        }
        try {
            var RZ = laytrans.property(ADBE.RotateZ).value;
            var sourceRect = layer.sourceRectAtTime(0, true);
            var CX = sourceRect.width * 0.5 + sourceRect.left;
            var CY = sourceRect.height * 0.5 + sourceRect.top;
            var scale = laytrans.property(ADBE.Scale).value;
            var SX = scale[0];
            var SY = scale[1];
            var anchor = laytrans.property(ADBE.AnchorPoint).value;
            var APX = anchor[0];
            var APY = anchor[1];
            var PX = 0;
            var PY = 0;
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                var pos = laytrans.property(ADBE.Position).value;
                PX = pos[0];
                PY = pos[1];
            }
            else {
                PX = laytrans.property(ADBE.Position_0).value;
                PY = laytrans.property(ADBE.Position_1).value;
            }
            laytrans.property(ADBE.AnchorPoint).setValue([0, 0, 0]);
            if (pet === 1) {
                layer
                    .property(ADBE.RootVectorsGroup)
                    .property(1)
                    .property(3)
                    .property('ADBE Vector Anchor').setValue([CX, CY]);
            }
            else if (pet === 2) {
                layer
                    .property(ADBE.RootVectorsGroup)
                    .property(1)
                    .property(2)
                    .property(1)
                    .property(3)
                    .property('ADBE Vector Anchor').setValue([CX, CY]);
            }
            else {
                laytrans.property(ADBE.AnchorPoint).setValue([CX, CY, 0]);
            }
            var DX = (CX - APX) * 0.01 * SX;
            var DY = (CY - APY) * 0.01 * SY;
            var rotRad = (RZ * Math.PI) / 180;
            var newX = PX + DX * Math.cos(rotRad) - DY * Math.sin(rotRad);
            var newY = PY + DX * Math.sin(rotRad) + DY * Math.cos(rotRad);
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                laytrans.property(ADBE.Position).setValue([newX, newY, 0]);
            }
            else {
                laytrans.property(ADBE.Position_0).setValue(newX);
                laytrans.property(ADBE.Position_1).setValue(newY);
            }
        }
        catch (e) {
        }
    }

    // Decompose a TextLayer into per-character shape layers.
    //
    // This is the algorithm that powers:
    //   - Baramoji_shape.jsx
    //   - Baramoji_shape_win.jsx
    //   - the "Shapes" button in Baramoji.jsx
    //
    // Algorithm (verbatim from the original .jsx):
    //   1. Convert selected text layer to shapes (executeCommand 3781).
    //   2. Duplicate the resulting shape group N times (one per glyph).
    //   3. In each duplicate, strip all but the matching glyph from Contents.
    //   4. Name each dup "char_<ch>" and align its in/out points to the source.
    //   5. Adjust its anchor point to the visual centre and shift its position
    //      so it stays in place.
    //   6. Move the duplicate before the source text layer.
    //   7. Disable the source text layer and remove the original shape group.
    //   8. Select the result layers.
    function runDecomposeTextToShapeLayers(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToShape);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionShape);
                app.endUndoGroup();
                return;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(4, 'Inspecting layers...');
            var selLayers = comp.selectedLayers;
            if (!selLayers || selLayers.length === 0) {
                alert(ALERT.NoLayersShape);
                app.endUndoGroup();
                return;
            }
            for (var layerIdx = 0; layerIdx < selLayers.length; layerIdx++) {
                var layerSpan = 60;
                var layerBase = 8 + Math.round((layerIdx / Math.max(1, selLayers.length)) * 10);
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(layerBase, 18), 'Processing layer ' + (layerIdx + 1) + '/' + selLayers.length + '...');
                var textLayer = selLayers[layerIdx];
                if (!(textLayer instanceof globalThis.TextLayer)) {
                    continue;
                }
                var layerInPoint = textLayer.inPoint;
                var layerOutPoint = textLayer.outPoint;
                var textContent = String(textLayer.text.sourceText.value);
                var cleanedForChars = textContent.replace(/\r|\n|/g, '');
                var cleanText = cleanedForChars.replace(/\s+/g, '');
                for (var sdel = 0; sdel < comp.selectedLayers.length; sdel++) {
                    comp.selectedLayers[sdel].selected = false;
                }
                textLayer.selected = true;
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(20, 'Converting text to shapes...');
                app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                var baseShapeLayer = comp.selectedLayers[0];
                if (!baseShapeLayer) {
                    alert(ALERT.FailedShapesFromText + textLayer.name);
                    continue;
                }
                var shapeContents = baseShapeLayer.property(ADBE.Contents);
                var totalShapes = shapeContents.numProperties;
                var resultLayers = [];
                for (var i = totalShapes - 1; i >= 0; i--) {
                    var dup = baseShapeLayer.duplicate();
                    var dupContents = dup.property(ADBE.Contents);
                    for (var j = dupContents.numProperties; j > 0; j--) {
                        if (j !== i + 1) {
                            try {
                                dupContents.property(j).remove();
                            }
                            catch (e) {
                                void e;
                            }
                        }
                    }
                    var charName = cleanText[i] ? cleanText[i] : String(i + 1);
                    dup.name = 'char_' + charName;
                    dup.inPoint = layerInPoint;
                    dup.outPoint = layerOutPoint;
                    adjustAnchorPoint(dup, 0);
                    try {
                        dup.moveBefore(textLayer);
                    }
                    catch (e) {
                        void e;
                    }
                    resultLayers.push(dup);
                    if (onProgress) {
                        var progressBase = 22;
                        var step = progressBase +
                            Math.round(((totalShapes - 1 - i) / Math.max(1, totalShapes)) * layerSpan);
                        onProgress(step, 'Isolating shape ' + (totalShapes - i) + '/' + totalShapes + '...');
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(86, 'Cleaning up...');
                try {
                    textLayer.enabled = false;
                }
                catch (e) {
                    void e;
                }
                try {
                    baseShapeLayer.remove();
                }
                catch (e) {
                    void e;
                }
                for (var rr = 0; rr < resultLayers.length; rr++) {
                    try {
                        resultLayers[rr].selected = true;
                    }
                    catch (e) {
                        void e;
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(90 + Math.round(((layerIdx + 1) / selLayers.length) * 8), 98), 'Layer ' + (layerIdx + 1) + '/' + selLayers.length + ' completed');
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(99, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }

    // Decompose a TextLayer (or ShapeLayer with vector content) into per-part
    // shape layers using path signed-area + point-in-polygon merge logic.
    //
    // This is the algorithm that powers:
    //   - Baramoji_part.jsx
    //   - Baramoji_part_win.jsx
    //   - the "Parts" button in Baramoji.jsx
    //
    // The algorithm is verbatim from the original .jsx (Copyright 2025 361do_sleep)
    // with type annotations added and shared helpers factored into `properties.ts` /
    // `anchor.ts`. Logic MUST stay byte-identical so the result matches the legacy
    // output.
    function runDecomposeTextToShapeParts(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToParts);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionParts);
                app.endUndoGroup();
                return;
            }
            var selectedLayers = comp.selectedLayers;
            if (selectedLayers.length === 0) {
                alert(ALERT.NoLayersParts);
                app.endUndoGroup();
                return;
            }
            try {
                var textLayerIndices = [];
                var layerProperties = [];
                for (var i = 0; i < selectedLayers.length; i++) {
                    var layer = selectedLayers[i];
                    var isTextLayer = layer instanceof globalThis.TextLayer;
                    var isShapeLayer = layer instanceof globalThis.AVLayer || layer.constructor.name === 'ShapeLayer';
                    var hasVectorGroup = false;
                    try {
                        hasVectorGroup = layer.property(ADBE.RootVectorsGroup) !== null;
                    }
                    catch (e) {
                        hasVectorGroup = false;
                    }
                    if (isTextLayer || (isShapeLayer && hasVectorGroup)) {
                        textLayerIndices.push(layer.index);
                        layerProperties.push(captureBasicProperties(layer));
                    }
                    layer.selected = false;
                }
                textLayerIndices.sort(function (a, b) { return a - b; });
                if (textLayerIndices.length === 0) {
                    alert(ALERT.NoValidForParts);
                    app.endUndoGroup();
                    return;
                }
                var totalSteps = Math.max(1, textLayerIndices.length);
                for (var i = 0; i < textLayerIndices.length; i++) {
                    var layerIndex = textLayerIndices[i];
                    var originalProps = layerProperties[i];
                    onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.round((i / totalSteps) * 80), 'Processing layer ' + (i + 1) + '/' + totalSteps + '...');
                    var currentLayer = comp.layers[layerIndex];
                    currentLayer.selected = true;
                    var baseShapeLayer = void 0;
                    if (currentLayer instanceof globalThis.TextLayer) {
                        app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                        baseShapeLayer =
                            comp.selectedLayers && comp.selectedLayers.length > 0
                                ? comp.selectedLayers[0]
                                : null;
                        if (!baseShapeLayer) {
                            alert(ALERT.FailedShapesFromTextA);
                            currentLayer.selected = false;
                            continue;
                        }
                    }
                    else {
                        try {
                            if (!currentLayer.property(ADBE.RootVectorsGroup)) {
                                alert(ALERT.FailedShapesNoVector + currentLayer.name);
                                currentLayer.selected = false;
                                continue;
                            }
                            baseShapeLayer = currentLayer;
                        }
                        catch (e) {
                            alert('Error processing shape layer: ' + e.toString());
                            currentLayer.selected = false;
                            continue;
                        }
                    }
                    var shapeLabel = undefined;
                    try {
                        shapeLabel = baseShapeLayer.label;
                    }
                    catch (e) {
                        void e;
                    }
                    processPartsMerge(baseShapeLayer);
                    var keepOriginal = currentLayer.constructor.name === 'ShapeLayer';
                    var resultLayers = processPartsDecompose(baseShapeLayer, originalProps, shapeLabel, keepOriginal);
                    if (resultLayers && resultLayers.length > 0) {
                        try {
                            for (var s = 0; s < comp.selectedLayers.length; s++) {
                                comp.selectedLayers[s].selected = false;
                            }
                            for (var r = 0; r < resultLayers.length; r++) {
                                resultLayers[r].selected = true;
                            }
                        }
                        catch (e) {
                            void e;
                        }
                    }
                }
            }
            catch (error) {
                alert('Error occurred: ' + error.toString());
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(95, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }
    /**
     * Merge overlapping paths inside the shape layer's "ADBE Root Vectors Group"
     * using signed-area + point-in-polygon tests. Identical to the original
     * Baramoji_part.jsx implementation.
     */
    function processPartsMerge(layer) {
        var vectorGroup = layer.property(ADBE.RootVectorsGroup);
        var prowloop = 1;
        while (prowloop <= vectorGroup.numProperties) {
            var pathcount = 1;
            var pathnum = 3;
            var nowtext = vectorGroup.property(prowloop).property(2);
            if (nowtext.numProperties === 3) {
                pathnum--;
            }
            var area = [];
            var maxarea = 0;
            var mavec = true;
            var pathveccheckloop = 1;
            var areavecchash = [];
            var pathnowloop = 0;
            while (pathveccheckloop <= nowtext.numProperties - pathnum) {
                var nexdex = 0;
                var areachash = 0;
                var nowpath = nowtext.property(pathveccheckloop).property(2);
                var nowpathpoint = nowpath.value.vertices;
                for (var i = 0; i < nowpathpoint.length; i++) {
                    nexdex = (i + 1) % nowpathpoint.length;
                    areachash += nowpathpoint[i][0] * nowpathpoint[nexdex][1];
                    areachash -= nowpathpoint[nexdex][0] * nowpathpoint[i][1];
                }
                if (Math.abs(areachash) > Math.abs(maxarea)) {
                    maxarea = areachash;
                }
                areavecchash[pathveccheckloop - 1] = areachash;
                pathveccheckloop++;
            }
            if (maxarea > 0) {
                mavec = false;
            }
            while (pathcount <= nowtext.numProperties - pathnum) {
                area[pathcount - 1] = areavecchash[pathnowloop];
                if ((area[pathcount - 1] < 0) === mavec) {
                    var countloop = 1;
                    var areamove = false;
                    nowtext.addProperty(ADBE.VectorGroup).moveTo(pathcount);
                    nowtext.property(pathcount).property(ADBE.VectorMaterialsGroup).remove();
                    nowtext.property(pathcount).name = nowtext.property(pathcount + 1).name;
                    nowtext.property(pathcount).property(2).addProperty(ADBE.VectorShapeGroup);
                    nowtext
                        .property(pathcount)
                        .property(2)
                        .property(1)
                        .property(2)
                        .setValue(nowtext.property(pathcount + 1).property(2).value);
                    nowtext.property(pathcount).property(2).property(1).name = nowtext.property(pathcount + 1).name;
                    nowtext.property(pathcount + 1).remove();
                    while (countloop < pathcount) {
                        if (area[countloop - 1] < area[pathcount - 1]) {
                            nowtext.property(pathcount).moveTo(countloop);
                            area.splice(countloop - 1, 0, area[pathcount - 1]);
                            areamove = true;
                        }
                        countloop++;
                    }
                    if (!areamove) {
                        nowtext.property(pathcount).moveTo(countloop);
                    }
                    pathcount++;
                }
                else {
                    nowtext.property(pathcount).moveTo(nowtext.numProperties - 3);
                    pathnum++;
                }
                pathnowloop++;
            }
            var countloop2 = 1;
            while (countloop2 < pathcount) {
                var contentsloop = 0;
                var Mflag = false;
                while (contentsloop < nowtext.numProperties - (pathcount + 2)) {
                    var ppflag = false;
                    var checkpoint = [
                        nowtext.property(pathcount + contentsloop).property(2).value.vertices[0][0],
                        nowtext.property(pathcount + contentsloop).property(2).value.vertices[0][1],
                    ];
                    var cn = 0;
                    var nowtexpath = nowtext
                        .property(countloop2)
                        .property(2)
                        .property(1)
                        .property(2);
                    var nowpathpoint = nowtexpath.value.vertices;
                    var nowpathoutT = nowtexpath.value.outTangents;
                    var nowpathinT = nowtexpath.value.inTangents;
                    var bezposX = [];
                    var bezposY = [];
                    for (var k = 0; k < nowpathpoint.length; k++) {
                        var beznexdex = (k + 1) % nowpathpoint.length;
                        var bez3 = 0.125;
                        var p0 = [nowpathpoint[k][0], nowpathpoint[k][1]];
                        var p1 = [
                            nowpathpoint[k][0] + nowpathoutT[k][0],
                            nowpathpoint[k][1] + nowpathoutT[k][1],
                        ];
                        var p2 = [
                            nowpathpoint[beznexdex][0] + nowpathinT[beznexdex][0],
                            nowpathpoint[beznexdex][1] + nowpathinT[beznexdex][1],
                        ];
                        var p3 = [nowpathpoint[beznexdex][0], nowpathpoint[beznexdex][1]];
                        bezposX[k] = bez3 * p0[0] + 3 * bez3 * p1[0] + 3 * bez3 * p2[0] + bez3 * p3[0];
                        bezposY[k] = bez3 * p0[1] + 3 * bez3 * p1[1] + 3 * bez3 * p2[1] + bez3 * p3[1];
                    }
                    var u = 0;
                    var bppointpos = [];
                    for (var j = 0; j < nowpathpoint.length * 2; j++) {
                        if (j % 2 === 0) {
                            bppointpos[j] = nowpathpoint[u];
                        }
                        else {
                            bppointpos[j] = [bezposX[u], bezposY[u]];
                            u++;
                        }
                    }
                    for (var i = 0; i < bppointpos.length; i++) {
                        var nexdex = (i + 1) % bppointpos.length;
                        if ((bppointpos[i][1] <= checkpoint[1] && bppointpos[nexdex][1] > checkpoint[1]) ||
                            (bppointpos[i][1] > checkpoint[1] && bppointpos[nexdex][1] <= checkpoint[1])) {
                            var vt = (checkpoint[1] - bppointpos[i][1]) / (bppointpos[nexdex][1] - bppointpos[i][1]);
                            if (checkpoint[0] <
                                bppointpos[i][0] + vt * (bppointpos[nexdex][0] - bppointpos[i][0])) {
                                cn++;
                            }
                        }
                    }
                    ppflag = cn % 2 !== 0;
                    if (ppflag) {
                        nowtext.property(countloop2).property(2).addProperty(ADBE.VectorShapeGroup).moveTo(2);
                        nowtext
                            .property(countloop2)
                            .property(2)
                            .property(2)
                            .property(2)
                            .setValue(nowtext.property(pathcount + contentsloop).property(2).value);
                        nowtext.property(countloop2).property(2).property(2).name =
                            nowtext.property(pathcount + contentsloop).name;
                        nowtext.property(pathcount + contentsloop).remove();
                        contentsloop--;
                        if (!Mflag) {
                            nowtext.property(countloop2).property(2).addProperty(ADBE.VectorFilterMerge);
                            Mflag = true;
                        }
                    }
                    contentsloop++;
                }
                countloop2++;
            }
            prowloop++;
        }
    }
    /**
     * Produce one duplicated layer per character outline from the merged
     * vector group.
     */
    function processPartsDecompose(layer, originalProps, targetLabel, keepOriginal) {
        var vectorGroup = layer.property(ADBE.RootVectorsGroup);
        var proloop = 0;
        var texnum = vectorGroup.numProperties;
        var resultLayers = [];
        while (proloop < texnum) {
            var character = vectorGroup.property(1);
            var contents = character.property(2);
            var pronum = contents.numProperties - 3;
            var prowloop = 1;
            while (prowloop < pronum) {
                var duplicatedLayer = layer.duplicate();
                duplicatedLayer.name = character.name + ' Outline ';
                var dupContents = duplicatedLayer
                    .property(ADBE.RootVectorsGroup)
                    .property(1)
                    .property(2);
                while (dupContents.numProperties > 4) {
                    dupContents.property(2).remove();
                }
                if (dupContents.property(2).matchName === ADBE.VectorFilterMerge) {
                    dupContents.property(2).remove();
                }
                contents.property(1).remove();
                while (duplicatedLayer.property(ADBE.RootVectorsGroup).numProperties > 1) {
                    duplicatedLayer.property(ADBE.RootVectorsGroup).property(2).remove();
                }
                adjustAnchorPoint(duplicatedLayer, 2);
                applyBasicProperties(duplicatedLayer, originalProps);
                if (typeof targetLabel !== 'undefined') {
                    try {
                        duplicatedLayer.label = targetLabel;
                    }
                    catch (e) {
                    }
                }
                try {
                    if (resultLayers.length === 0) {
                        duplicatedLayer.moveBefore(layer);
                    }
                    else {
                        var lastLayer = resultLayers[resultLayers.length - 1];
                        duplicatedLayer.moveBefore(lastLayer);
                    }
                }
                catch (e) {
                }
                resultLayers.push(duplicatedLayer);
                prowloop++;
            }
            var finalLayer = layer.duplicate();
            finalLayer.name = character.name + ' Outline ';
            var finalContents = finalLayer
                .property(ADBE.RootVectorsGroup)
                .property(1)
                .property(2);
            if (finalContents.property(2).matchName === ADBE.VectorFilterMerge) {
                finalContents.property(2).remove();
            }
            while (finalLayer.property(ADBE.RootVectorsGroup).numProperties > 1) {
                finalLayer.property(ADBE.RootVectorsGroup).property(2).remove();
            }
            adjustAnchorPoint(finalLayer, 2);
            applyBasicProperties(finalLayer, originalProps);
            if (typeof targetLabel !== 'undefined') {
                try {
                    finalLayer.label = targetLabel;
                }
                catch (e) {
                }
            }
            try {
                if (resultLayers.length === 0) {
                    finalLayer.moveBefore(layer);
                }
                else {
                    var lastLayer = resultLayers[resultLayers.length - 1];
                    finalLayer.moveBefore(lastLayer);
                }
            }
            catch (e) {
            }
            resultLayers.push(finalLayer);
            vectorGroup.property(1).remove();
            proloop++;
        }
        if (keepOriginal) {
            try {
                layer.enabled = false;
            }
            catch (e) {
            }
        }
        else {
            try {
                layer.remove();
            }
            catch (e) {
            }
        }
        return resultLayers;
    }

    // Decompose a TextLayer into per-character text layers (preserving per-char
    // styling and positions).
    //
    // This is the algorithm that powers:
    //   - Baramoji_txt.jsx
    //   - Baramoji_txt_win.jsx
    //   - the "Texts" button in Baramoji.jsx
    //
    // Logic MUST stay byte-identical to the original (Copyright 2025 361do_sleep).
    function runDecomposeTextToTextLayers(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToText);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionText);
                app.endUndoGroup();
                return;
            }
            var curTime = comp.time;
            var selLayers = comp.selectedLayers;
            if (!selLayers || selLayers.length === 0) {
                alert(ALERT.NoLayersText);
                app.endUndoGroup();
                return;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(4, 'Inspecting layers...');
            for (var layerIdx = 0; layerIdx < selLayers.length; layerIdx++) {
                var layerBase = 8 + Math.round((layerIdx / Math.max(1, selLayers.length)) * 10);
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(layerBase, 18), 'Processing layer ' + (layerIdx + 1) + '/' + selLayers.length + '...');
                var textLayer = selLayers[layerIdx];
                if (!(textLayer instanceof globalThis.TextLayer)) {
                    continue;
                }
                if (hasDeepGlow(textLayer)) {
                    alert(ALERT.RemoveDeepGlow + textLayer.name);
                    continue;
                }
                var originalScale = [100, 100];
                try {
                    var s = textLayer.transform.scale.value;
                    if (s.length === 2)
                        originalScale = [s[0], s[1]];
                    else if (s.length === 3)
                        originalScale = [s[0], s[1]];
                }
                catch (e) {
                    void e;
                }
                var originalSolo = false;
                try {
                    originalSolo = textLayer.solo === true;
                }
                catch (e) {
                    void e;
                }
                var layerInPoint = textLayer.inPoint;
                var layerOutPoint = textLayer.outPoint;
                var originalText = textLayer.text.sourceText.value;
                var textContent = String(originalText);
                var cleanedForChars = textContent.replace(//g, '');
                var textFontSize = getPropertyArray('fontSize', textLayer).split(',');
                var textFont = getPropertyArray('font', textLayer).split(',');
                var textApplyFill = getPropertyArray('applyFill', textLayer).split(',');
                var textFillColor_txt = getPropertyArray('fillColor', textLayer).split(',');
                var textApplyStroke = getPropertyArray('applyStroke', textLayer).split(',');
                var textStrokeColor_txt = getPropertyArray('strokeColor', textLayer).split(',');
                var textStrokeWidth = getPropertyArray('strokeWidth', textLayer).split(',');
                var textTracking = getPropertyArray('tracking', textLayer).split(',');
                var textBaselineShift = getPropertyArray('baselineShift', textLayer).split(',');
                var textStrokeOverFill = getPropertyArray('strokeOverFill', textLayer).split(',');
                var textFauxBold = getPropertyArray('fauxBold', textLayer).split(',');
                var textFauxItalic = getPropertyArray('fauxItalic', textLayer).split(',');
                var textTsume = getPropertyArray('tsume', textLayer).split(',');
                var textFillColor = [];
                for (var i = 0; i < textFillColor_txt.length; i += 3) {
                    textFillColor.push(textFillColor_txt.slice(i, i + 3));
                }
                var textStrokeColor = [];
                for (var i = 0; i < textStrokeColor_txt.length; i += 3) {
                    textStrokeColor.push(textStrokeColor_txt.slice(i, i + 3));
                }
                var specialCharRegex = /[\s\n\r]/g;
                var specialCharIndices = [];
                var text = cleanedForChars;
                for (var ci = 0; ci < text.length; ci++) {
                    if (specialCharRegex.test(text[ci]))
                        specialCharIndices.push(ci);
                }
                var cleanText = text.replace(/\s+/g, '');
                for (var j = specialCharIndices.length - 1; j >= 0; j--) {
                    var idx = specialCharIndices[j];
                    if (textFontSize.length > idx)
                        textFontSize.splice(idx, 1);
                    if (textFont.length > idx)
                        textFont.splice(idx, 1);
                    if (textApplyFill.length > idx)
                        textApplyFill.splice(idx, 1);
                    if (textFillColor.length > idx)
                        textFillColor.splice(idx, 1);
                    if (textApplyStroke.length > idx)
                        textApplyStroke.splice(idx, 1);
                    if (textStrokeColor.length > idx)
                        textStrokeColor.splice(idx, 1);
                    if (textStrokeWidth.length > idx)
                        textStrokeWidth.splice(idx, 1);
                    if (textTracking.length > idx)
                        textTracking.splice(idx, 1);
                    if (textBaselineShift.length > idx)
                        textBaselineShift.splice(idx, 1);
                    if (textStrokeOverFill.length > idx)
                        textStrokeOverFill.splice(idx, 1);
                    if (textFauxBold.length > idx)
                        textFauxBold.splice(idx, 1);
                    if (textFauxItalic.length > idx)
                        textFauxItalic.splice(idx, 1);
                    if (textTsume.length > idx)
                        textTsume.splice(idx, 1);
                }
                for (var sdel = 0; sdel < comp.selectedLayers.length; sdel++) {
                    comp.selectedLayers[sdel].selected = false;
                }
                textLayer.selected = true;
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(20, 'Converting text to shapes...');
                app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                var shapeLayer = comp.selectedLayers[0];
                if (!shapeLayer) {
                    alert(ALERT.FailedShapesFromText + textLayer.name);
                    continue;
                }
                var shapeContents = shapeLayer.property(ADBE.Contents);
                for (var p = shapeContents.numProperties - 1; p > 0; p--) {
                    var duplicatedShape = comp.selectedLayers[0].duplicate();
                    duplicatedShape.selected = true;
                }
                var allShapes = comp.selectedLayers;
                for (var si = 0; si < allShapes.length; si++) {
                    var curShape = allShapes[si];
                    curShape.enabled = false;
                    var curContents = curShape.property(ADBE.Contents);
                    for (var pi = curContents.numProperties; pi > 0; pi--) {
                        if (pi !== si + 1) {
                            try {
                                curContents.property(pi).remove();
                            }
                            catch (e) {
                                void e;
                            }
                        }
                    }
                }
                var shapeAnchorX = [];
                var shapeAnchorY = [];
                var shapePositionX = [];
                var shapePositionY = [];
                for (var s = 0; s < allShapes.length; s++) {
                    try {
                        var cur = allShapes[s];
                        var shapeRot = cur.transform.rotation
                            ? cur.transform.rotation.value
                            : 0;
                        var shapeAnchor = cur.transform.anchorPoint.value;
                        var shapeBounds = cur.sourceRectAtTime(curTime, false);
                        var centerX = shapeBounds.width / 2 + shapeBounds.left;
                        var centerY = shapeBounds.height / 2 + shapeBounds.top;
                        var offsetX = (centerX - shapeAnchor[0]) * (originalScale[0] / 100);
                        var offsetY = (centerY - shapeAnchor[1]) * (originalScale[1] / 100);
                        var cosR = Math.cos((shapeRot * Math.PI) / 180);
                        var sinR = Math.sin((shapeRot * Math.PI) / 180);
                        var shpPos = cur.transform.position.value;
                        shapeAnchorX.push(centerX);
                        shapeAnchorY.push(centerY);
                        shapePositionX.push(shpPos[0] + offsetX * cosR - offsetY * sinR);
                        shapePositionY.push(shpPos[1] + offsetX * sinR + offsetY * cosR);
                    }
                    catch (e) {
                        void e;
                        shapeAnchorX.push(0);
                        shapeAnchorY.push(0);
                        var baseP = textLayer.transform.position.value;
                        shapePositionX.push(baseP[0]);
                        shapePositionY.push(baseP[1]);
                    }
                }
                var resultLayers = [];
                for (var ci = cleanText.length - 1; ci >= 0; ci--) {
                    var characterLayer = textLayer.duplicate();
                    characterLayer.enabled = true;
                    characterLayer.name = cleanText[ci];
                    try {
                        characterLayer.solo = originalSolo;
                    }
                    catch (e) {
                        void e;
                    }
                    resultLayers.unshift(characterLayer);
                }
                var baseProgress = 22;
                var span = 60;
                for (var charIndex = 0; charIndex < cleanText.length; charIndex++) {
                    var characterLayer = resultLayers[charIndex];
                    var charTextDocument = textLayer.text.sourceText.valueAtTime(curTime, true);
                    charTextDocument.text = cleanText[charIndex];
                    try {
                        if (charIndex < textFontSize.length) {
                            if (textFontSize[charIndex] !== '') {
                                charTextDocument.fontSize = Number(textFontSize[charIndex]);
                            }
                            if (textFont[charIndex] !== '') {
                                charTextDocument.font = textFont[charIndex];
                            }
                            if (textApplyFill[charIndex] === 'true') {
                                charTextDocument.applyFill = true;
                                if (textFillColor[charIndex]) {
                                    charTextDocument.fillColor = textFillColor[charIndex];
                                }
                            }
                            else {
                                charTextDocument.applyFill = false;
                            }
                            if (textApplyStroke[charIndex] === 'true') {
                                charTextDocument.applyStroke = true;
                                if (textStrokeColor[charIndex]) {
                                    charTextDocument.strokeColor = textStrokeColor[charIndex];
                                }
                                if (textStrokeWidth[charIndex] !== '') {
                                    charTextDocument.strokeWidth = Number(textStrokeWidth[charIndex]);
                                }
                            }
                            else {
                                charTextDocument.applyStroke = false;
                            }
                            if (textTracking[charIndex] !== undefined && textTracking[charIndex] !== '') {
                                charTextDocument.tracking = Number(textTracking[charIndex]);
                            }
                            if (textBaselineShift[charIndex] !== undefined && textBaselineShift[charIndex] !== '') {
                                charTextDocument.baselineShift = Number(textBaselineShift[charIndex]);
                            }
                            if (textStrokeOverFill[charIndex] !== undefined) {
                                charTextDocument.strokeOverFill = textStrokeOverFill[charIndex] === 'true';
                            }
                            if (textFauxBold[charIndex] !== undefined) {
                                charTextDocument.fauxBold = textFauxBold[charIndex] === 'true';
                            }
                            if (textFauxItalic[charIndex] !== undefined) {
                                charTextDocument.fauxItalic = textFauxItalic[charIndex] === 'true';
                            }
                            if (textTsume[charIndex] !== undefined && textTsume[charIndex] !== '') {
                                charTextDocument.tsume = Number(textTsume[charIndex]);
                            }
                        }
                    }
                    catch (styleError) {
                        void styleError;
                    }
                    characterLayer.text.sourceText.setValue(charTextDocument);
                    try {
                        var tSize = getLayerSize(characterLayer);
                        var sSize = getLayerSize(allShapes[charIndex]);
                        var originalHScale = charTextDocument.horizontalScale || 100;
                        var originalVScale = charTextDocument.verticalScale || 100;
                        var newHScale = (sSize[0] / (tSize[0] || 1)) * originalHScale;
                        var newVScale = (sSize[1] / (tSize[1] || 1)) * originalVScale;
                        charTextDocument.horizontalScale = Math.min(Math.max(newHScale, 0), 1000);
                        charTextDocument.verticalScale = Math.min(Math.max(newVScale, 0), 1000);
                        characterLayer.text.sourceText.setValue(charTextDocument);
                    }
                    catch (e) {
                        void e;
                    }
                    try {
                        var lb = characterLayer.sourceRectAtTime(curTime, false);
                        var charAnchorLocal = [
                            lb.width / 2 + lb.left,
                            lb.height / 2 + lb.top,
                        ];
                        try {
                            characterLayer.transform.anchorPoint.setValue(charAnchorLocal);
                        }
                        catch (e) {
                            void e;
                        }
                        var textAP = textLayer.transform.anchorPoint.value;
                        var sx = shapeAnchorX[charIndex];
                        var sy = shapeAnchorY[charIndex];
                        var localOffsetX = (sx - textAP[0]) * (originalScale[0] / 100);
                        var localOffsetY = (sy - textAP[1]) * (originalScale[1] / 100);
                        var localOffsetZ = 0;
                        if (!textLayer.threeDLayer) {
                            var rotZ = textLayer.transform.rotation
                                ? textLayer.transform.rotation.value
                                : 0;
                            var cosR = Math.cos(degToRad(rotZ));
                            var sinR = Math.sin(degToRad(rotZ));
                            var rotX = localOffsetX * cosR - localOffsetY * sinR;
                            var rotY = localOffsetX * sinR + localOffsetY * cosR;
                            var basePos = textLayer.transform.position.value;
                            var finalX = basePos[0] + rotX;
                            var finalY = basePos[1] + rotY;
                            try {
                                if (!characterLayer.transform.position.dimensionsSeparated) {
                                    setPosition(characterLayer.transform.property(ADBE.Position), [finalX, finalY]);
                                }
                                else {
                                    setPosition(characterLayer.transform.property(ADBE.Position_0), finalX);
                                    setPosition(characterLayer.transform.property(ADBE.Position_1), finalY);
                                }
                            }
                            catch (e) {
                                try {
                                    characterLayer.transform.position.setValue([finalX, finalY]);
                                }
                                catch (e2) {
                                    void e2;
                                }
                            }
                        }
                        else {
                            var ori = [0, 0, 0];
                            try {
                                var oriVal = textLayer.transform.orientation.value;
                                if (oriVal && oriVal.length >= 3) {
                                    ori = [oriVal[0], oriVal[1], oriVal[2]];
                                }
                            }
                            catch (e) {
                                void e;
                            }
                            var xRot = textLayer.transform.xRotation
                                ? textLayer.transform.xRotation.value
                                : 0;
                            var yRot = textLayer.transform.yRotation
                                ? textLayer.transform.yRotation.value
                                : 0;
                            var zRot = textLayer.transform.zRotation
                                ? textLayer.transform.zRotation.value
                                : 0;
                            var rotationVals = [xRot, yRot, zRot];
                            var oriMat = rotationToMatrix(ori);
                            var rotMat = rotationToMatrix(rotationVals);
                            var finalMat = multiplyMatrix3x3(oriMat, rotMat);
                            var applied = applyMatrixToOffset(finalMat, localOffsetX, localOffsetY, localOffsetZ);
                            var basePos = textLayer.transform.position.value;
                            var finalPos3 = [
                                basePos[0] + applied[0],
                                basePos[1] + applied[1],
                                (basePos.length > 2 ? basePos[2] : 0) + (applied[2] || 0),
                            ];
                            try {
                                if (!characterLayer.transform.position.dimensionsSeparated) {
                                    setPosition(characterLayer.transform.property(ADBE.Position), finalPos3);
                                }
                                else {
                                    setPosition(characterLayer.transform.property(ADBE.Position_0), finalPos3[0]);
                                    setPosition(characterLayer.transform.property(ADBE.Position_1), finalPos3[1]);
                                    if (characterLayer.transform.property(ADBE.Position_2)) {
                                        setPosition(characterLayer.transform.property(ADBE.Position_2), finalPos3[2]);
                                    }
                                }
                            }
                            catch (e) {
                                try {
                                    characterLayer.transform.position.setValue(finalPos3);
                                }
                                catch (e2) {
                                    void e2;
                                }
                            }
                        }
                    }
                    catch (posError) {
                        try {
                            characterLayer.transform.position.setValue(textLayer.transform.position.value);
                        }
                        catch (e2) {
                            void e2;
                        }
                    }
                    characterLayer.inPoint = layerInPoint;
                    characterLayer.outPoint = layerOutPoint;
                    if (onProgress) {
                        onProgress(baseProgress + Math.round((charIndex / Math.max(1, cleanText.length)) * span), 'Styling character ' + (charIndex + 1) + '/' + cleanText.length + '...');
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(86, 'Cleaning up...');
                try {
                    textLayer.enabled = false;
                }
                catch (e) {
                    void e;
                }
                for (var rem = 0; rem < allShapes.length; rem++) {
                    try {
                        allShapes[rem].remove();
                    }
                    catch (e) {
                        void e;
                    }
                }
                try {
                    for (var ss = 0; ss < comp.selectedLayers.length; ss++) {
                        comp.selectedLayers[ss].selected = false;
                    }
                }
                catch (e) {
                    void e;
                }
                for (var rr = 0; rr < resultLayers.length; rr++) {
                    try {
                        resultLayers[rr].selected = true;
                    }
                    catch (e) {
                        void e;
                    }
                }
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(99, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }

    // Baramoji.jsx entry — combined UI palette for all three decompositions.
    // Original: Baramoji.jsx (Copyright 2025 361do_sleep).
    (function BaramojiEntry() {
        var win = buildPalette({
            onTexts: function () { return runDecomposeTextToTextLayers(); },
            onShapes: function () { return runDecomposeTextToShapeLayers(); },
            onParts: function () { return runDecomposeTextToShapeParts(); }
        });
        win.center();
        win.show();
    })();

})();
