// Baramoji — MIT License
// Copyright (c) 2025 361do_sleep (original)
// Copyright (c) 2025 rebuildup and contributors (TypeScript port)
// Source: https://github.com/rebuildup/Ae_Baramoji_ts
//
// This file is auto-generated from src/entries/*.ts.
// Do not edit this file directly — modify the TypeScript source instead.

(function () {
    'use strict';

    // ExtendScript ES3 polyfills.
    //
    // ExtendScript's JavaScript engine is based on ES3 and is missing several
    // standard methods. Loading this file at the top of every entry guarantees
    // those methods exist before any user code runs.
    //
    // Rollup inlines this into every output .jsx, so the polyfills are baked in
    // without changing the runtime semantics of any later code.
    //
    // We use `any` here deliberately: TypeScript's lib knows about Array.prototype.indexOf etc.
    // (because it's an ES5 type), but ExtendScript's runtime doesn't have them.
    // The whole point of this file is to install them.
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // eslint-disable-next-line no-var
    var ArrayProto = Array.prototype;
    // eslint-disable-next-line no-var
    var StringProto = String.prototype;
    // Array.prototype.indexOf — ES5
    if (typeof ArrayProto.indexOf !== 'function') {
        ArrayProto.indexOf = function (searchElement, fromIndex) {
            var start = fromIndex || 0;
            var len = this.length;
            if (start < 0)
                start = Math.max(len + start, 0);
            for (var i = start; i < len; i++) {
                if (this[i] === searchElement)
                    return i;
            }
            return -1;
        };
    }
    // Array.prototype.forEach — ES5 (ExtendScript often ships this, but guard)
    if (typeof ArrayProto.forEach !== 'function') {
        ArrayProto.forEach = function (callback, thisArg) {
            for (var i = 0; i < this.length; i++) {
                callback.call(thisArg, this[i], i, this);
            }
        };
    }
    // Array.prototype.map — ES5
    if (typeof ArrayProto.map !== 'function') {
        ArrayProto.map = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                result.push(callback.call(thisArg, this[i], i, this));
            }
            return result;
        };
    }
    // Array.prototype.filter — ES5
    if (typeof ArrayProto.filter !== 'function') {
        ArrayProto.filter = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                if (callback.call(thisArg, this[i], i, this))
                    result.push(this[i]);
            }
            return result;
        };
    }
    // String.prototype.trim — ES5
    if (typeof StringProto.trim !== 'function') {
        StringProto.trim = function () {
            return this.replace(/^\s+|\s+$/g, '');
        };
    }
    // Object.keys — ES5
    if (typeof Object.keys !== 'function') {
        Object.keys = function (obj) {
            var keys = [];
            for (var k in obj) {
                if (Object.prototype.hasOwnProperty.call(obj, k))
                    keys.push(k);
            }
            return keys;
        };
    }
    // Note: src/types/*.d.ts are picked up by tsconfig include, so no runtime
    // import is needed (and .d.ts files don't generate runtime code anyway).

    // Shared constants for the Baramoji decomposition algorithms.
    /** AE internal menu command that converts the selected TextLayer into ShapeLayers. */
    var CMD_CREATE_TEXT_SHAPE = 3781;
    // ADBE match names (stable across AE versions; "matchName" / "matchNames").
    var ADBE = {
        TransformGroup: 'ADBE Transform Group',
        Position: 'ADBE Position',
        Position_0: 'ADBE Position_0',
        Position_1: 'ADBE Position_1',
        Position_2: 'ADBE Position_2',
        AnchorPoint: 'ADBE Anchor Point',
        Scale: 'ADBE Scale',
        RotateZ: 'ADBE Rotate Z',
        XRotation: 'ADBE X Rotation',
        YRotation: 'ADBE Y Rotation',
        ZRotation: 'ADBE Z Rotation',
        Orientation: 'ADBE Orientation',
        RootVectorsGroup: 'ADBE Root Vectors Group',
        VectorGroup: 'ADBE Vector Group',
        VectorMaterialsGroup: 'ADBE Vector Materials Group',
        VectorShapeGroup: 'ADBE Vector Shape - Group',
        VectorFilterMerge: 'ADBE Vector Filter - Merge',
        VectorAnchor: 'ADBE Vector Anchor',
        Contents: 'Contents',
        SourceText: 'Source Text',
        EffectParade: 'ADBE Effect Parade',
        PEDG: 'PEDG',
        PEDG2: 'PEDG2'
    };
    // Undo group names — used for AE's undo system.
    var UNDO = {
        DecomposeTextToText: 'DecomposeTextLayers',
        DecomposeTextToShape: 'DecomposeTextToShapeLayers',
        DecomposeTextToParts: 'Text to Parts Decompose'
    };
    /** Localised label / description for each DuplicateMode (used by palette + _win modal). */
    var DUPLICATE_MODE_LABEL = {
        skip: {
            name: 'Skip existing',
            description: 'Skip source layers that already have a decomposition in this comp.'
        },
        overwrite: {
            name: 'Overwrite',
            description: 'Delete the previous decomposition and re-run from scratch.'
        },
        cancel: {
            name: 'Cancel (do nothing)',
            description: 'Abort the run if any selected layer already has a decomposition.'
        }
    };
    // Default alert / dialog text.
    var ALERT = {
        NoCompositionText: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionShape: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionParts: 'No composition is active. Please open a composition and select text layers or shape layers.',
        NoLayersText: 'No layers selected. Please select one or more text layers.',
        NoLayersShape: 'No layers selected. Please select one or more text layers.',
        NoLayersParts: 'No layers selected. Please select one or more text layers or shape layers.',
        FailedShapesFromText: 'Failed to create shapes from text for layer: ',
        FailedShapesFromTextA: 'Failed to create shapes from text for a layer.',
        FailedShapesNoVector: 'Selected layer does not contain vector content: ',
        NoValidForParts: 'No valid text layers or shape layers found in selection. Please select layers with vector content.',
        RemoveDeepGlow: 'Please temporarily remove the Deep Glow effect from the layer: '
    };

    // ProgressDialog — a small ScriptUI helper used by the _win variants.
    //
    // Extends AE's Window/palette with progressbar + status text + an
    // updateProgress(value, text) method. Identical to what the original
    // _win .jsx files built by hand.
    // We don't actually use the ProgressDialog class — the makeProgressHelpers
    // factory constructs a fresh ScriptUI palette inline. This keeps the
    // runtime behaviour byte-identical to the original _win .jsx files.
    /**
     * The original _win variants embed a 4-line helper directly into the IIFE.
     * This module-level helper mirrors that behaviour but is called from a
     * single place, so all _win entries get identical UX.
     */
    function makeProgressHelpers(opts) {
        var dlg = null;
        function show() {
            if (!dlg || !dlg.visible) {
                var Win = globalThis.Window;
                dlg = new Win('palette', opts.title, undefined);
                dlg.orientation = 'column';
                dlg.alignChildren = ['fill', 'center'];
                dlg.bar = dlg.add('progressbar', undefined, 0, 100);
                dlg.bar.preferredSize = { width: 300 };
                dlg.status = dlg.add('statictext', [0, 0, 300, 30], 'Preparing...');
                dlg.status.alignment = 'center';
                dlg.updateProgress = function (target, text) {
                    if (!dlg.bar)
                        return;
                    var cur = Math.round(dlg.bar.value) || 0;
                    var tgt = Math.max(0, Math.min(100, Math.round(target || 0)));
                    var next = Math.max(cur, tgt);
                    dlg.bar.value = next;
                    dlg.status.text = text || String(next) + '% complete';
                    try {
                        dlg.update();
                    }
                    catch (e) {
                    }
                };
                dlg.center();
                dlg.show();
            }
        }
        function update(value, text) {
            if (dlg && dlg.updateProgress) {
                dlg.updateProgress(value, text);
            }
        }
        function close() {
            if (dlg) {
                try {
                    dlg.close();
                }
                catch (e) {
                }
                dlg = null;
            }
        }
        return { show: show, update: update, close: close };
    }

    // Build the ScriptUI palette shown by Baramoji.jsx (the unified entry).
    //
    // Three buttons — Texts, Shapes, Parts — each wired to one of the three
    // decomposition algorithms via the onProgress stub passed by the entry file.
    // A dropdown above the buttons selects how existing decomposition artifacts
    // should be handled (see DUPLICATE_MODE_LABEL).
    var MODE_ORDER = ['skip', 'overwrite', 'cancel'];
    /**
     * Standalone modal dialog for the per-algorithm `_win` variants. Shows a
     * radio button group for the duplicate mode. Returns null if the user
     * cancels.
     */
    function promptDuplicateMode(initial) {
        if (initial === void 0) { initial = 'skip'; }
        var Win = globalThis.Window;
        var dlg = new Win('dialog', 'Baramoji', undefined);
        dlg.orientation = 'column';
        dlg.alignChildren = ['fill', 'top'];
        dlg.add('statictext', undefined, 'How should existing decomposition be handled?');
        var radios = [];
        for (var _i = 0, MODE_ORDER_1 = MODE_ORDER; _i < MODE_ORDER_1.length; _i++) {
            var mode = MODE_ORDER_1[_i];
            var rb = dlg.add('radiobutton', undefined, DUPLICATE_MODE_LABEL[mode].name);
            rb.value = mode === initial;
            radios.push(rb);
        }
        var buttonRow = dlg.add('group');
        buttonRow.orientation = 'row';
        buttonRow.alignChildren = ['center', 'center'];
        var okBtn = buttonRow.add('button', undefined, 'OK');
        var cancelBtn = buttonRow.add('button', undefined, 'Cancel');
        okBtn.onClick = function () {
            dlg._result = 'ok';
            dlg.close();
        };
        cancelBtn.onClick = function () {
            dlg._result = 'cancel';
            dlg.close();
        };
        dlg.center();
        dlg.show();
        if (dlg._result !== 'ok')
            return null;
        for (var i = 0; i < radios.length; i++) {
            if (radios[i].value)
                return MODE_ORDER[i];
        }
        return initial;
    }

    // adjustAnchorPoint — the anchor/position math that appears in both
    // Baramoji_shape.jsx (inline) and Baramoji_part.jsx (extracted as
    // `adjustAnchorPoint`). The `_part` version accepts a `pet` parameter to
    // control where the vector anchor is set; we preserve that here.
    /**
     * Move a layer's anchor point to the visual center of its sourceRect and
     * apply the inverse translation to its position so the layer visually
     * stays in place. No-op if the transform group has keyframes.
     *
     * @param pet 0 = transform-group anchor; 1 = root vectors group anchor;
     *            2 = nested (1).property(2).property(1) anchor (used in parts).
     */
    function adjustAnchorPoint(layer, pet) {
        var laytrans = layer.property(ADBE.TransformGroup);
        if (!laytrans)
            return;
        // Skip if any of these are animated.
        if (laytrans.property(ADBE.Position).numKeys !== 0 ||
            laytrans.property(ADBE.Position_0).numKeys !== 0 ||
            laytrans.property(ADBE.Position_1).numKeys !== 0 ||
            laytrans.property(ADBE.AnchorPoint).numKeys !== 0) {
            return;
        }
        try {
            var RZ = laytrans.property(ADBE.RotateZ).value;
            var sourceRect = layer.sourceRectAtTime(0, true);
            var CX = sourceRect.width * 0.5 + sourceRect.left;
            var CY = sourceRect.height * 0.5 + sourceRect.top;
            var scale = laytrans.property(ADBE.Scale).value;
            var SX = scale[0];
            var SY = scale[1];
            var anchor = laytrans.property(ADBE.AnchorPoint).value;
            var APX = anchor[0];
            var APY = anchor[1];
            var PX = 0;
            var PY = 0;
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                var pos = laytrans.property(ADBE.Position).value;
                PX = pos[0];
                PY = pos[1];
            }
            else {
                PX = laytrans.property(ADBE.Position_0).value;
                PY = laytrans.property(ADBE.Position_1).value;
            }
            laytrans.property(ADBE.AnchorPoint).setValue([0, 0, 0]);
            if (pet === 1) ;
            else if (pet === 2) ;
            else {
                laytrans.property(ADBE.AnchorPoint).setValue([CX, CY, 0]);
            }
            var DX = (CX - APX) * 0.01 * SX;
            var DY = (CY - APY) * 0.01 * SY;
            var rotRad = (RZ * Math.PI) / 180;
            var newX = PX + DX * Math.cos(rotRad) - DY * Math.sin(rotRad);
            var newY = PY + DX * Math.sin(rotRad) + DY * Math.cos(rotRad);
            if (!laytrans.property(ADBE.Position).dimensionsSeparated) {
                laytrans.property(ADBE.Position).setValue([newX, newY, 0]);
            }
            else {
                laytrans.property(ADBE.Position_0).setValue(newX);
                laytrans.property(ADBE.Position_1).setValue(newY);
            }
        }
        catch (e) {
        }
    }

    // Heuristics for detecting and removing artifacts left in a comp by a
    // previous run of the decomposition algorithms.
    //
    // Each algorithm leaves layers with distinctive names. We use those names as
    // a best-effort signal of "this comp already has a decomposition". Users who
    // happen to have unrelated layers with matching names can pre-select to
    // avoid false positives.
    //
    // Algorithm → naming convention:
    //   - text decomposition: per-character TextLayer whose name is the single
    //     character (possibly filtered through the same charFilter the algorithm
    //     applies). See `nameTextArtifact`.
    //   - shape decomposition: per-character ShapeLayer named "char_<char>".
    //     See `nameShapeArtifact`.
    //   - parts decomposition: per-part ShapeLayer named "<partName> Outline ".
    //     See `namePartsArtifact`.
    /**
     * Return true if `sourceLayer` looks like it already has been decomposed
     * inside `comp` by `algorithm`. The check is best-effort and only inspects
     * siblings within the same comp.
     */
    function hasDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return false;
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer))
                return true;
        }
        return false;
    }
    /**
     * Remove any layer in `comp` (other than `sourceLayer` itself) that looks
     * like an artifact of a previous `algorithm` run. Returns the count of
     * removed layers. Detection is the same heuristic as `hasDecompositionArtifacts`.
     */
    function removeDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return 0;
        // Collect matching layers first; removing while iterating mutates indices.
        var toRemove = [];
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer))
                toRemove.push(layer);
        }
        for (var _i = 0, toRemove_1 = toRemove; _i < toRemove_1.length; _i++) {
            var layer = toRemove_1[_i];
            try {
                layer.remove();
            }
            catch (e) {
            }
        }
        return toRemove.length;
    }
    function matchesArtifact(layer, sourceLayer, algorithm) {
        if (!layer || !layer.name)
            return false;
        var name = String(layer.name);
        {
            // Shape decomposition names: "char_<char>" or "char_<char>_<idx>".
            return name.indexOf('char_') === 0 && name.length > 5;
        }
    }

    // Decompose a TextLayer into per-character shape layers.
    //
    // This is the algorithm that powers:
    //   - Baramoji_shape.jsx
    //   - Baramoji_shape_win.jsx
    //   - the "Shapes" button in Baramoji.jsx
    //
    // Algorithm (verbatim from the original .jsx):
    //   1. Convert selected text layer to shapes (executeCommand 3781).
    //   2. Duplicate the resulting shape group N times (one per glyph).
    //   3. In each duplicate, strip all but the matching glyph from Contents.
    //   4. Name each dup "char_<ch>" and align its in/out points to the source.
    //   5. Adjust its anchor point to the visual centre and shift its position
    //      so it stays in place.
    //   6. Move the duplicate before the source text layer.
    //   7. Disable the source text layer and remove the original shape group.
    //   8. Select the result layers.
    function runDecomposeTextToShapeLayers(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress, _e = opts.duplicateMode, duplicateMode = _e === void 0 ? 'skip' : _e;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToShape);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionShape);
                app.endUndoGroup();
                return;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(4, 'Inspecting layers...');
            var selLayers = comp.selectedLayers;
            if (!selLayers || selLayers.length === 0) {
                alert(ALERT.NoLayersShape);
                app.endUndoGroup();
                return;
            }
            if (duplicateMode === 'cancel') {
                for (var i = 0; i < selLayers.length; i++) {
                    if (hasDecompositionArtifacts(comp, selLayers[i], 'shape')) {
                        alert('Aborted: a selected layer already has a shape decomposition. ' +
                            'Re-run with Skip or Overwrite to change existing layers.');
                        app.endUndoGroup();
                        return;
                    }
                }
            }
            for (var layerIdx = 0; layerIdx < selLayers.length; layerIdx++) {
                var layerSpan = 60;
                var layerBase = 8 + Math.round((layerIdx / Math.max(1, selLayers.length)) * 10);
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(layerBase, 18), 'Processing layer ' + (layerIdx + 1) + '/' + selLayers.length + '...');
                var textLayer = selLayers[layerIdx];
                if (!(textLayer instanceof globalThis.TextLayer)) {
                    continue;
                }
                if (duplicateMode === 'skip' && hasDecompositionArtifacts(comp, textLayer, 'shape')) {
                    onProgress === null || onProgress === void 0 ? void 0 : onProgress(layerBase, 'Skipping already-decomposed layer: ' + textLayer.name);
                    continue;
                }
                if (duplicateMode === 'overwrite') {
                    var removed = removeDecompositionArtifacts(comp, textLayer, 'shape');
                    if (removed > 0)
                        onProgress === null || onProgress === void 0 ? void 0 : onProgress(layerBase, 'Removed ' + removed + ' stale layer(s) for: ' + textLayer.name);
                }
                var layerInPoint = textLayer.inPoint;
                var layerOutPoint = textLayer.outPoint;
                var textContent = String(textLayer.text.sourceText.value);
                var cleanedForChars = textContent.replace(/\r|\n|/g, '');
                var cleanText = cleanedForChars.replace(/\s+/g, '');
                for (var sdel = 0; sdel < comp.selectedLayers.length; sdel++) {
                    comp.selectedLayers[sdel].selected = false;
                }
                textLayer.selected = true;
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(20, 'Converting text to shapes...');
                app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                var baseShapeLayer = comp.selectedLayers[0];
                if (!baseShapeLayer) {
                    alert(ALERT.FailedShapesFromText + textLayer.name);
                    continue;
                }
                var shapeContents = baseShapeLayer.property(ADBE.Contents);
                var totalShapes = shapeContents.numProperties;
                var resultLayers = [];
                for (var i = totalShapes - 1; i >= 0; i--) {
                    var dup = baseShapeLayer.duplicate();
                    var dupContents = dup.property(ADBE.Contents);
                    for (var j = dupContents.numProperties; j > 0; j--) {
                        if (j !== i + 1) {
                            try {
                                dupContents.property(j).remove();
                            }
                            catch (e) {
                                void e;
                            }
                        }
                    }
                    var charName = cleanText[i] ? cleanText[i] : String(i + 1);
                    dup.name = 'char_' + charName;
                    dup.inPoint = layerInPoint;
                    dup.outPoint = layerOutPoint;
                    adjustAnchorPoint(dup, 0);
                    try {
                        dup.moveBefore(textLayer);
                    }
                    catch (e) {
                        void e;
                    }
                    resultLayers.push(dup);
                    if (onProgress) {
                        var progressBase = 22;
                        var step = progressBase +
                            Math.round(((totalShapes - 1 - i) / Math.max(1, totalShapes)) * layerSpan);
                        onProgress(step, 'Isolating shape ' + (totalShapes - i) + '/' + totalShapes + '...');
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(86, 'Cleaning up...');
                try {
                    textLayer.enabled = false;
                }
                catch (e) {
                    void e;
                }
                try {
                    baseShapeLayer.remove();
                }
                catch (e) {
                    void e;
                }
                for (var rr = 0; rr < resultLayers.length; rr++) {
                    try {
                        resultLayers[rr].selected = true;
                    }
                    catch (e) {
                        void e;
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(90 + Math.round(((layerIdx + 1) / selLayers.length) * 8), 98), 'Layer ' + (layerIdx + 1) + '/' + selLayers.length + ' completed');
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(99, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }

    // Baramoji_shape_win.jsx entry — shape decomposition with progress window.
    // Original: Baramoji_shape_win.jsx (Copyright 2024 Nisai, 2025 361do_sleep).
    (function BaramojiShapeWinEntry() {
        var mode = promptDuplicateMode();
        if (mode === null)
            return;
        var progress = makeProgressHelpers({ title: 'Decompose Text To Shapes' });
        try {
            runDecomposeTextToShapeLayers({ onProgress: progress.update, duplicateMode: mode });
        }
        finally {
            progress.close();
        }
    })();

})();
