// Baramoji — MIT License
// Copyright (c) 2025 361do_sleep (original)
// Copyright (c) 2025 rebuildup and contributors (TypeScript port)
// Source: https://github.com/rebuildup/Ae_Baramoji_ts
//
// This file is auto-generated from src/entries/*.ts.
// Do not edit this file directly — modify the TypeScript source instead.

(function () {
    'use strict';

    // ExtendScript ES3 polyfills.
    //
    // ExtendScript's JavaScript engine is based on ES3 and is missing several
    // standard methods. Loading this file at the top of every entry guarantees
    // those methods exist before any user code runs.
    //
    // Rollup inlines this into every output .jsx, so the polyfills are baked in
    // without changing the runtime semantics of any later code.
    //
    // We use `any` here deliberately: TypeScript's lib knows about Array.prototype.indexOf etc.
    // (because it's an ES5 type), but ExtendScript's runtime doesn't have them.
    // The whole point of this file is to install them.
    /* eslint-disable @typescript-eslint/no-explicit-any */
    // eslint-disable-next-line no-var
    var ArrayProto = Array.prototype;
    // eslint-disable-next-line no-var
    var StringProto = String.prototype;
    // Array.prototype.indexOf — ES5
    if (typeof ArrayProto.indexOf !== 'function') {
        ArrayProto.indexOf = function (searchElement, fromIndex) {
            var start = fromIndex || 0;
            var len = this.length;
            if (start < 0)
                start = Math.max(len + start, 0);
            for (var i = start; i < len; i++) {
                if (this[i] === searchElement)
                    return i;
            }
            return -1;
        };
    }
    // Array.prototype.forEach — ES5 (ExtendScript often ships this, but guard)
    if (typeof ArrayProto.forEach !== 'function') {
        ArrayProto.forEach = function (callback, thisArg) {
            for (var i = 0; i < this.length; i++) {
                callback.call(thisArg, this[i], i, this);
            }
        };
    }
    // Array.prototype.map — ES5
    if (typeof ArrayProto.map !== 'function') {
        ArrayProto.map = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                result.push(callback.call(thisArg, this[i], i, this));
            }
            return result;
        };
    }
    // Array.prototype.filter — ES5
    if (typeof ArrayProto.filter !== 'function') {
        ArrayProto.filter = function (callback, thisArg) {
            var result = [];
            for (var i = 0; i < this.length; i++) {
                if (callback.call(thisArg, this[i], i, this))
                    result.push(this[i]);
            }
            return result;
        };
    }
    // String.prototype.trim — ES5
    if (typeof StringProto.trim !== 'function') {
        StringProto.trim = function () {
            return this.replace(/^\s+|\s+$/g, '');
        };
    }
    // Object.keys — ES5
    if (typeof Object.keys !== 'function') {
        Object.keys = function (obj) {
            var keys = [];
            for (var k in obj) {
                if (Object.prototype.hasOwnProperty.call(obj, k))
                    keys.push(k);
            }
            return keys;
        };
    }
    // Note: src/types/*.d.ts are picked up by tsconfig include, so no runtime
    // import is needed (and .d.ts files don't generate runtime code anyway).

    // Shared constants for the Baramoji decomposition algorithms.
    /** AE internal menu command that converts the selected TextLayer into ShapeLayers. */
    var CMD_CREATE_TEXT_SHAPE = 3781;
    // ADBE match names (stable across AE versions; "matchName" / "matchNames").
    var ADBE = {
        TransformGroup: 'ADBE Transform Group',
        Position: 'ADBE Position',
        Position_0: 'ADBE Position_0',
        Position_1: 'ADBE Position_1',
        Position_2: 'ADBE Position_2',
        AnchorPoint: 'ADBE Anchor Point',
        Scale: 'ADBE Scale',
        RotateZ: 'ADBE Rotate Z',
        XRotation: 'ADBE X Rotation',
        YRotation: 'ADBE Y Rotation',
        ZRotation: 'ADBE Z Rotation',
        Orientation: 'ADBE Orientation',
        RootVectorsGroup: 'ADBE Root Vectors Group',
        VectorGroup: 'ADBE Vector Group',
        VectorMaterialsGroup: 'ADBE Vector Materials Group',
        VectorShapeGroup: 'ADBE Vector Shape - Group',
        VectorFilterMerge: 'ADBE Vector Filter - Merge',
        VectorAnchor: 'ADBE Vector Anchor',
        Contents: 'Contents',
        SourceText: 'Source Text',
        EffectParade: 'ADBE Effect Parade',
        PEDG: 'PEDG',
        PEDG2: 'PEDG2'
    };
    // Undo group names — used for AE's undo system.
    var UNDO = {
        DecomposeTextToText: 'DecomposeTextLayers',
        DecomposeTextToShape: 'DecomposeTextToShapeLayers',
        DecomposeTextToParts: 'Text to Parts Decompose'
    };
    /** Localised label / description for each DuplicateMode (used by palette + _win modal). */
    var DUPLICATE_MODE_LABEL = {
        skip: {
            name: 'Skip existing',
            description: 'Skip source layers that already have a decomposition in this comp.'
        },
        overwrite: {
            name: 'Overwrite',
            description: 'Delete the previous decomposition and re-run from scratch.'
        },
        cancel: {
            name: 'Cancel (do nothing)',
            description: 'Abort the run if any selected layer already has a decomposition.'
        }
    };
    // Default alert / dialog text.
    var ALERT = {
        NoCompositionText: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionShape: 'No composition is active. Please open a composition and select text layers.',
        NoCompositionParts: 'No composition is active. Please open a composition and select text layers or shape layers.',
        NoLayersText: 'No layers selected. Please select one or more text layers.',
        NoLayersShape: 'No layers selected. Please select one or more text layers.',
        NoLayersParts: 'No layers selected. Please select one or more text layers or shape layers.',
        FailedShapesFromText: 'Failed to create shapes from text for layer: ',
        FailedShapesFromTextA: 'Failed to create shapes from text for a layer.',
        FailedShapesNoVector: 'Selected layer does not contain vector content: ',
        NoValidForParts: 'No valid text layers or shape layers found in selection. Please select layers with vector content.',
        RemoveDeepGlow: 'Please temporarily remove the Deep Glow effect from the layer: '
    };

    // ProgressDialog — a small ScriptUI helper used by the _win variants.
    //
    // Extends AE's Window/palette with progressbar + status text + an
    // updateProgress(value, text) method. Identical to what the original
    // _win .jsx files built by hand.
    // We don't actually use the ProgressDialog class — the makeProgressHelpers
    // factory constructs a fresh ScriptUI palette inline. This keeps the
    // runtime behaviour byte-identical to the original _win .jsx files.
    /**
     * The original _win variants embed a 4-line helper directly into the IIFE.
     * This module-level helper mirrors that behaviour but is called from a
     * single place, so all _win entries get identical UX.
     */
    function makeProgressHelpers(opts) {
        var dlg = null;
        function show() {
            if (!dlg || !dlg.visible) {
                var Win = globalThis.Window;
                dlg = new Win('palette', opts.title, undefined);
                dlg.orientation = 'column';
                dlg.alignChildren = ['fill', 'center'];
                dlg.bar = dlg.add('progressbar', undefined, 0, 100);
                dlg.bar.preferredSize = { width: 300 };
                dlg.status = dlg.add('statictext', [0, 0, 300, 30], 'Preparing...');
                dlg.status.alignment = 'center';
                dlg.updateProgress = function (target, text) {
                    if (!dlg.bar)
                        return;
                    var cur = Math.round(dlg.bar.value) || 0;
                    var tgt = Math.max(0, Math.min(100, Math.round(target || 0)));
                    var next = Math.max(cur, tgt);
                    dlg.bar.value = next;
                    dlg.status.text = text || String(next) + '% complete';
                    try {
                        dlg.update();
                    }
                    catch (e) {
                    }
                };
                dlg.center();
                dlg.show();
            }
        }
        function update(value, text) {
            if (dlg && dlg.updateProgress) {
                dlg.updateProgress(value, text);
            }
        }
        function close() {
            if (dlg) {
                try {
                    dlg.close();
                }
                catch (e) {
                }
                dlg = null;
            }
        }
        return { show: show, update: update, close: close };
    }

    // Build the ScriptUI palette shown by Baramoji.jsx (the unified entry).
    //
    // Three buttons — Texts, Shapes, Parts — each wired to one of the three
    // decomposition algorithms via the onProgress stub passed by the entry file.
    // A dropdown above the buttons selects how existing decomposition artifacts
    // should be handled (see DUPLICATE_MODE_LABEL).
    var MODE_ORDER = ['skip', 'overwrite', 'cancel'];
    /**
     * Standalone modal dialog for the per-algorithm `_win` variants. Shows a
     * radio button group for the duplicate mode. Returns null if the user
     * cancels.
     */
    function promptDuplicateMode(initial) {
        if (initial === void 0) { initial = 'skip'; }
        var Win = globalThis.Window;
        var dlg = new Win('dialog', 'Baramoji', undefined);
        dlg.orientation = 'column';
        dlg.alignChildren = ['fill', 'top'];
        dlg.add('statictext', undefined, 'How should existing decomposition be handled?');
        var radios = [];
        for (var _i = 0, MODE_ORDER_1 = MODE_ORDER; _i < MODE_ORDER_1.length; _i++) {
            var mode = MODE_ORDER_1[_i];
            var rb = dlg.add('radiobutton', undefined, DUPLICATE_MODE_LABEL[mode].name);
            rb.value = mode === initial;
            radios.push(rb);
        }
        var buttonRow = dlg.add('group');
        buttonRow.orientation = 'row';
        buttonRow.alignChildren = ['center', 'center'];
        var okBtn = buttonRow.add('button', undefined, 'OK');
        var cancelBtn = buttonRow.add('button', undefined, 'Cancel');
        okBtn.onClick = function () {
            dlg._result = 'ok';
            dlg.close();
        };
        cancelBtn.onClick = function () {
            dlg._result = 'cancel';
            dlg.close();
        };
        dlg.center();
        dlg.show();
        if (dlg._result !== 'ok')
            return null;
        for (var i = 0; i < radios.length; i++) {
            if (radios[i].value)
                return MODE_ORDER[i];
        }
        return initial;
    }

    // Property helpers for capturing and applying layer state.
    //
    // Used by both text decomposition (per-character style extraction) and parts
    // decomposition (preserve original layer attributes when duplicating).
    /** Set a property's value, falling back silently on animated properties. */
    function setPosition(prop, value) {
        if (!prop)
            return;
        if (prop.numKeys === 0) {
            prop.setValue(value);
        }
        else {
            try {
                prop.setValue(value);
            }
            catch (e) {
            }
        }
    }
    /**
     * Extract an array-valued TextLayer style attribute as a comma-separated
     * string by temporarily setting an expression. Original Baramoji_txt.jsx
     * uses this trick to read fontSize / fillColor / etc. per character.
     */
    function getPropertyArray(property, layer) {
        var txtSave = layer.property(ADBE.SourceText).value;
        var expression = 'var output_txt=[]; for(var i=0;i<text.sourceText.length;i++){output_txt.push(text.sourceText.getStyleAt(i).' +
            property +
            ');}output_txt;';
        layer.property(ADBE.SourceText).expression = expression;
        var output = layer.property(ADBE.SourceText).value;
        layer.property(ADBE.SourceText).expression = '';
        // Restore the original TextDocument (assigning to .value triggers setValue).
        layer.text.sourceText.setValue(txtSave);
        return String(output);
    }
    /** Get the source rect (size) of a layer at the comp's current time. */
    function getLayerSize(layer) {
        var comp = app.project.activeItem;
        var bounds = layer.sourceRectAtTime(comp.time, false);
        return [bounds.width, bounds.height];
    }
    /** Detect "Deep Glow" effect (the popular plugin) on a layer. */
    function hasDeepGlow(layer) {
        try {
            var ef = layer.property(ADBE.EffectParade);
            if (!ef)
                return false;
            if (ef.property(ADBE.PEDG) || ef.property(ADBE.PEDG2))
                return true;
        }
        catch (e) {
        }
        return false;
    }

    // 3D rotation math used by the text decomposition algorithm.
    //
    // AE text layers can be 3D, so positioning each decomposed character layer
    // requires composing rotation matrices. The original Baramoji_txt.jsx
    // inlines these helpers; we extract them here for sharing with other
    // entries.
    function degToRad(deg) {
        return (deg * Math.PI) / 180;
    }
    /**
     * Convert a 3D rotation vector (degrees) into a rotation matrix.
     * Standard Euler-angle convention: rot = [xDeg, yDeg, zDeg].
     */
    function rotationToMatrix(rot) {
        var rx = degToRad(rot[0]);
        var ry = degToRad(rot[1]);
        var rz = degToRad(rot[2]);
        var cosX = Math.cos(rx);
        var sinX = Math.sin(rx);
        var cosY = Math.cos(ry);
        var sinY = Math.sin(ry);
        var cosZ = Math.cos(rz);
        var sinZ = Math.sin(rz);
        return [
            [cosY * cosZ, -cosY * sinZ, sinY],
            [sinX * sinY * cosZ + cosX * sinZ, -sinX * sinY * sinZ + cosX * cosZ, -sinX * cosY],
            [-cosX * sinY * cosZ + sinX * sinZ, cosX * sinY * sinZ + sinX * cosZ, cosX * cosY],
        ];
    }
    function multiplyMatrix3x3(a, b) {
        var r = [
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0],
        ];
        for (var i = 0; i < 3; i++) {
            for (var j = 0; j < 3; j++) {
                r[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
            }
        }
        return r;
    }
    function applyMatrixToOffset(matrix, x, y, z) {
        return [
            x * matrix[0][0] + y * matrix[0][1] + z * matrix[0][2],
            x * matrix[1][0] + y * matrix[1][1] + z * matrix[1][2],
            x * matrix[2][0] + y * matrix[2][1] + z * matrix[2][2],
        ];
    }

    // Heuristics for detecting and removing artifacts left in a comp by a
    // previous run of the decomposition algorithms.
    //
    // Each algorithm leaves layers with distinctive names. We use those names as
    // a best-effort signal of "this comp already has a decomposition". Users who
    // happen to have unrelated layers with matching names can pre-select to
    // avoid false positives.
    //
    // Algorithm → naming convention:
    //   - text decomposition: per-character TextLayer whose name is the single
    //     character (possibly filtered through the same charFilter the algorithm
    //     applies). See `nameTextArtifact`.
    //   - shape decomposition: per-character ShapeLayer named "char_<char>".
    //     See `nameShapeArtifact`.
    //   - parts decomposition: per-part ShapeLayer named "<partName> Outline ".
    //     See `namePartsArtifact`.
    /**
     * Return true if `sourceLayer` looks like it already has been decomposed
     * inside `comp` by `algorithm`. The check is best-effort and only inspects
     * siblings within the same comp.
     */
    function hasDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return false;
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer, sourceLayer))
                return true;
        }
        return false;
    }
    /**
     * Remove any layer in `comp` (other than `sourceLayer` itself) that looks
     * like an artifact of a previous `algorithm` run. Returns the count of
     * removed layers. Detection is the same heuristic as `hasDecompositionArtifacts`.
     */
    function removeDecompositionArtifacts(comp, sourceLayer, algorithm) {
        if (!comp || !sourceLayer)
            return 0;
        // Collect matching layers first; removing while iterating mutates indices.
        var toRemove = [];
        for (var i = 1; i <= comp.numLayers; i++) {
            var layer = comp.layer(i);
            if (layer === sourceLayer)
                continue;
            if (matchesArtifact(layer, sourceLayer))
                toRemove.push(layer);
        }
        for (var _i = 0, toRemove_1 = toRemove; _i < toRemove_1.length; _i++) {
            var layer = toRemove_1[_i];
            try {
                layer.remove();
            }
            catch (e) {
            }
        }
        return toRemove.length;
    }
    function matchesArtifact(layer, sourceLayer, algorithm) {
        if (!layer || !layer.name)
            return false;
        var name = String(layer.name);
        {
            // Single-character name that appears in the source text (best-effort).
            if (name.length !== 1)
                return false;
            try {
                var src = String(sourceLayer.text.sourceText.value);
                return src.replace(/\s/g, '').indexOf(name) >= 0;
            }
            catch (e) {
                return false;
            }
        }
        return false;
    }

    // Decompose a TextLayer into per-character text layers (preserving per-char
    // styling and positions).
    //
    // This is the algorithm that powers:
    //   - Baramoji_txt.jsx
    //   - Baramoji_txt_win.jsx
    //   - the "Texts" button in Baramoji.jsx
    //
    // Logic MUST stay byte-identical to the original (Copyright 2025 361do_sleep).
    function runDecomposeTextToTextLayers(opts) {
        var _a, _b, _c, _d;
        if (opts === void 0) { opts = {}; }
        var onProgress = opts.onProgress, _e = opts.duplicateMode, duplicateMode = _e === void 0 ? 'skip' : _e;
        try {
            app.beginUndoGroup(UNDO.DecomposeTextToText);
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(0, 'Initializing...');
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof globalThis.CompItem)) {
                alert(ALERT.NoCompositionText);
                app.endUndoGroup();
                return;
            }
            var curTime = comp.time;
            var selLayers = comp.selectedLayers;
            if (!selLayers || selLayers.length === 0) {
                alert(ALERT.NoLayersText);
                app.endUndoGroup();
                return;
            }
            // Cancel-mode short-circuit: if ANY selected layer already looks
            // decomposed, abort before doing any work.
            if (duplicateMode === 'cancel') {
                for (var i = 0; i < selLayers.length; i++) {
                    if (hasDecompositionArtifacts(comp, selLayers[i], 'text')) {
                        alert('Aborted: a selected layer already has a text decomposition. ' +
                            'Re-run with Skip or Overwrite to change existing layers.');
                        app.endUndoGroup();
                        return;
                    }
                }
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(4, 'Inspecting layers...');
            for (var layerIdx = 0; layerIdx < selLayers.length; layerIdx++) {
                var layerBase = 8 + Math.round((layerIdx / Math.max(1, selLayers.length)) * 10);
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(Math.min(layerBase, 18), 'Processing layer ' + (layerIdx + 1) + '/' + selLayers.length + '...');
                var textLayer = selLayers[layerIdx];
                if (!(textLayer instanceof globalThis.TextLayer)) {
                    continue;
                }
                if (hasDeepGlow(textLayer)) {
                    alert(ALERT.RemoveDeepGlow + textLayer.name);
                    continue;
                }
                // Skip / overwrite handling: check this source layer's siblings.
                if (duplicateMode === 'skip' && hasDecompositionArtifacts(comp, textLayer, 'text')) {
                    onProgress === null || onProgress === void 0 ? void 0 : onProgress(layerBase, 'Skipping already-decomposed layer: ' + textLayer.name);
                    continue;
                }
                if (duplicateMode === 'overwrite') {
                    var removed = removeDecompositionArtifacts(comp, textLayer, 'text');
                    if (removed > 0)
                        onProgress === null || onProgress === void 0 ? void 0 : onProgress(layerBase, 'Removed ' + removed + ' stale layer(s) for: ' + textLayer.name);
                }
                var originalScale = [100, 100];
                try {
                    var s = textLayer.transform.scale.value;
                    if (s.length === 2)
                        originalScale = [s[0], s[1]];
                    else if (s.length === 3)
                        originalScale = [s[0], s[1]];
                }
                catch (e) {
                    void e;
                }
                var originalSolo = false;
                try {
                    originalSolo = textLayer.solo === true;
                }
                catch (e) {
                    void e;
                }
                var layerInPoint = textLayer.inPoint;
                var layerOutPoint = textLayer.outPoint;
                var originalText = textLayer.text.sourceText.value;
                var textContent = String(originalText);
                var cleanedForChars = textContent.replace(//g, '');
                var textFontSize = getPropertyArray('fontSize', textLayer).split(',');
                var textFont = getPropertyArray('font', textLayer).split(',');
                var textApplyFill = getPropertyArray('applyFill', textLayer).split(',');
                var textFillColor_txt = getPropertyArray('fillColor', textLayer).split(',');
                var textApplyStroke = getPropertyArray('applyStroke', textLayer).split(',');
                var textStrokeColor_txt = getPropertyArray('strokeColor', textLayer).split(',');
                var textStrokeWidth = getPropertyArray('strokeWidth', textLayer).split(',');
                var textTracking = getPropertyArray('tracking', textLayer).split(',');
                var textBaselineShift = getPropertyArray('baselineShift', textLayer).split(',');
                var textStrokeOverFill = getPropertyArray('strokeOverFill', textLayer).split(',');
                var textFauxBold = getPropertyArray('fauxBold', textLayer).split(',');
                var textFauxItalic = getPropertyArray('fauxItalic', textLayer).split(',');
                var textTsume = getPropertyArray('tsume', textLayer).split(',');
                var textFillColor = [];
                for (var i = 0; i < textFillColor_txt.length; i += 3) {
                    textFillColor.push(textFillColor_txt.slice(i, i + 3));
                }
                var textStrokeColor = [];
                for (var i = 0; i < textStrokeColor_txt.length; i += 3) {
                    textStrokeColor.push(textStrokeColor_txt.slice(i, i + 3));
                }
                var specialCharRegex = /[\s\n\r]/g;
                var specialCharIndices = [];
                var text = cleanedForChars;
                for (var ci = 0; ci < text.length; ci++) {
                    if (specialCharRegex.test(text[ci]))
                        specialCharIndices.push(ci);
                }
                var cleanText = text.replace(/\s+/g, '');
                for (var j = specialCharIndices.length - 1; j >= 0; j--) {
                    var idx = specialCharIndices[j];
                    if (textFontSize.length > idx)
                        textFontSize.splice(idx, 1);
                    if (textFont.length > idx)
                        textFont.splice(idx, 1);
                    if (textApplyFill.length > idx)
                        textApplyFill.splice(idx, 1);
                    if (textFillColor.length > idx)
                        textFillColor.splice(idx, 1);
                    if (textApplyStroke.length > idx)
                        textApplyStroke.splice(idx, 1);
                    if (textStrokeColor.length > idx)
                        textStrokeColor.splice(idx, 1);
                    if (textStrokeWidth.length > idx)
                        textStrokeWidth.splice(idx, 1);
                    if (textTracking.length > idx)
                        textTracking.splice(idx, 1);
                    if (textBaselineShift.length > idx)
                        textBaselineShift.splice(idx, 1);
                    if (textStrokeOverFill.length > idx)
                        textStrokeOverFill.splice(idx, 1);
                    if (textFauxBold.length > idx)
                        textFauxBold.splice(idx, 1);
                    if (textFauxItalic.length > idx)
                        textFauxItalic.splice(idx, 1);
                    if (textTsume.length > idx)
                        textTsume.splice(idx, 1);
                }
                for (var sdel = 0; sdel < comp.selectedLayers.length; sdel++) {
                    comp.selectedLayers[sdel].selected = false;
                }
                textLayer.selected = true;
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(20, 'Converting text to shapes...');
                app.executeCommand(CMD_CREATE_TEXT_SHAPE);
                var shapeLayer = comp.selectedLayers[0];
                if (!shapeLayer) {
                    alert(ALERT.FailedShapesFromText + textLayer.name);
                    continue;
                }
                var shapeContents = shapeLayer.property(ADBE.Contents);
                for (var p = shapeContents.numProperties - 1; p > 0; p--) {
                    var duplicatedShape = comp.selectedLayers[0].duplicate();
                    duplicatedShape.selected = true;
                }
                var allShapes = comp.selectedLayers;
                for (var si = 0; si < allShapes.length; si++) {
                    var curShape = allShapes[si];
                    curShape.enabled = false;
                    var curContents = curShape.property(ADBE.Contents);
                    for (var pi = curContents.numProperties; pi > 0; pi--) {
                        if (pi !== si + 1) {
                            try {
                                curContents.property(pi).remove();
                            }
                            catch (e) {
                                void e;
                            }
                        }
                    }
                }
                var shapeAnchorX = [];
                var shapeAnchorY = [];
                var shapePositionX = [];
                var shapePositionY = [];
                for (var s = 0; s < allShapes.length; s++) {
                    try {
                        var cur = allShapes[s];
                        var shapeRot = cur.transform.rotation
                            ? cur.transform.rotation.value
                            : 0;
                        var shapeAnchor = cur.transform.anchorPoint.value;
                        var shapeBounds = cur.sourceRectAtTime(curTime, false);
                        var centerX = shapeBounds.width / 2 + shapeBounds.left;
                        var centerY = shapeBounds.height / 2 + shapeBounds.top;
                        var offsetX = (centerX - shapeAnchor[0]) * (originalScale[0] / 100);
                        var offsetY = (centerY - shapeAnchor[1]) * (originalScale[1] / 100);
                        var cosR = Math.cos((shapeRot * Math.PI) / 180);
                        var sinR = Math.sin((shapeRot * Math.PI) / 180);
                        var shpPos = cur.transform.position.value;
                        shapeAnchorX.push(centerX);
                        shapeAnchorY.push(centerY);
                        shapePositionX.push(shpPos[0] + offsetX * cosR - offsetY * sinR);
                        shapePositionY.push(shpPos[1] + offsetX * sinR + offsetY * cosR);
                    }
                    catch (e) {
                        void e;
                        shapeAnchorX.push(0);
                        shapeAnchorY.push(0);
                        var baseP = textLayer.transform.position.value;
                        shapePositionX.push(baseP[0]);
                        shapePositionY.push(baseP[1]);
                    }
                }
                var resultLayers = [];
                for (var ci = cleanText.length - 1; ci >= 0; ci--) {
                    var characterLayer = textLayer.duplicate();
                    characterLayer.enabled = true;
                    characterLayer.name = cleanText[ci];
                    try {
                        characterLayer.solo = originalSolo;
                    }
                    catch (e) {
                        void e;
                    }
                    resultLayers.unshift(characterLayer);
                }
                var baseProgress = 22;
                var span = 60;
                for (var charIndex = 0; charIndex < cleanText.length; charIndex++) {
                    var characterLayer = resultLayers[charIndex];
                    var charTextDocument = textLayer.text.sourceText.valueAtTime(curTime, true);
                    charTextDocument.text = cleanText[charIndex];
                    try {
                        if (charIndex < textFontSize.length) {
                            if (textFontSize[charIndex] !== '') {
                                charTextDocument.fontSize = Number(textFontSize[charIndex]);
                            }
                            if (textFont[charIndex] !== '') {
                                charTextDocument.font = textFont[charIndex];
                            }
                            if (textApplyFill[charIndex] === 'true') {
                                charTextDocument.applyFill = true;
                                if (textFillColor[charIndex]) {
                                    charTextDocument.fillColor = textFillColor[charIndex];
                                }
                            }
                            else {
                                charTextDocument.applyFill = false;
                            }
                            if (textApplyStroke[charIndex] === 'true') {
                                charTextDocument.applyStroke = true;
                                if (textStrokeColor[charIndex]) {
                                    charTextDocument.strokeColor = textStrokeColor[charIndex];
                                }
                                if (textStrokeWidth[charIndex] !== '') {
                                    charTextDocument.strokeWidth = Number(textStrokeWidth[charIndex]);
                                }
                            }
                            else {
                                charTextDocument.applyStroke = false;
                            }
                            if (textTracking[charIndex] !== undefined && textTracking[charIndex] !== '') {
                                charTextDocument.tracking = Number(textTracking[charIndex]);
                            }
                            if (textBaselineShift[charIndex] !== undefined && textBaselineShift[charIndex] !== '') {
                                charTextDocument.baselineShift = Number(textBaselineShift[charIndex]);
                            }
                            if (textStrokeOverFill[charIndex] !== undefined) {
                                charTextDocument.strokeOverFill = textStrokeOverFill[charIndex] === 'true';
                            }
                            if (textFauxBold[charIndex] !== undefined) {
                                charTextDocument.fauxBold = textFauxBold[charIndex] === 'true';
                            }
                            if (textFauxItalic[charIndex] !== undefined) {
                                charTextDocument.fauxItalic = textFauxItalic[charIndex] === 'true';
                            }
                            if (textTsume[charIndex] !== undefined && textTsume[charIndex] !== '') {
                                charTextDocument.tsume = Number(textTsume[charIndex]);
                            }
                        }
                    }
                    catch (styleError) {
                        void styleError;
                    }
                    characterLayer.text.sourceText.setValue(charTextDocument);
                    try {
                        var tSize = getLayerSize(characterLayer);
                        var sSize = getLayerSize(allShapes[charIndex]);
                        var originalHScale = charTextDocument.horizontalScale || 100;
                        var originalVScale = charTextDocument.verticalScale || 100;
                        var newHScale = (sSize[0] / (tSize[0] || 1)) * originalHScale;
                        var newVScale = (sSize[1] / (tSize[1] || 1)) * originalVScale;
                        charTextDocument.horizontalScale = Math.min(Math.max(newHScale, 0), 1000);
                        charTextDocument.verticalScale = Math.min(Math.max(newVScale, 0), 1000);
                        characterLayer.text.sourceText.setValue(charTextDocument);
                    }
                    catch (e) {
                        void e;
                    }
                    try {
                        var lb = characterLayer.sourceRectAtTime(curTime, false);
                        var charAnchorLocal = [
                            lb.width / 2 + lb.left,
                            lb.height / 2 + lb.top,
                        ];
                        try {
                            characterLayer.transform.anchorPoint.setValue(charAnchorLocal);
                        }
                        catch (e) {
                            void e;
                        }
                        var textAP = textLayer.transform.anchorPoint.value;
                        var sx = shapeAnchorX[charIndex];
                        var sy = shapeAnchorY[charIndex];
                        var localOffsetX = (sx - textAP[0]) * (originalScale[0] / 100);
                        var localOffsetY = (sy - textAP[1]) * (originalScale[1] / 100);
                        var localOffsetZ = 0;
                        if (!textLayer.threeDLayer) {
                            var rotZ = textLayer.transform.rotation
                                ? textLayer.transform.rotation.value
                                : 0;
                            var cosR = Math.cos(degToRad(rotZ));
                            var sinR = Math.sin(degToRad(rotZ));
                            var rotX = localOffsetX * cosR - localOffsetY * sinR;
                            var rotY = localOffsetX * sinR + localOffsetY * cosR;
                            var basePos = textLayer.transform.position.value;
                            var finalX = basePos[0] + rotX;
                            var finalY = basePos[1] + rotY;
                            try {
                                if (!characterLayer.transform.position.dimensionsSeparated) {
                                    setPosition(characterLayer.transform.property(ADBE.Position), [finalX, finalY]);
                                }
                                else {
                                    setPosition(characterLayer.transform.property(ADBE.Position_0), finalX);
                                    setPosition(characterLayer.transform.property(ADBE.Position_1), finalY);
                                }
                            }
                            catch (e) {
                                try {
                                    characterLayer.transform.position.setValue([finalX, finalY]);
                                }
                                catch (e2) {
                                    void e2;
                                }
                            }
                        }
                        else {
                            var ori = [0, 0, 0];
                            try {
                                var oriVal = textLayer.transform.orientation.value;
                                if (oriVal && oriVal.length >= 3) {
                                    ori = [oriVal[0], oriVal[1], oriVal[2]];
                                }
                            }
                            catch (e) {
                                void e;
                            }
                            var xRot = textLayer.transform.xRotation
                                ? textLayer.transform.xRotation.value
                                : 0;
                            var yRot = textLayer.transform.yRotation
                                ? textLayer.transform.yRotation.value
                                : 0;
                            var zRot = textLayer.transform.zRotation
                                ? textLayer.transform.zRotation.value
                                : 0;
                            var rotationVals = [xRot, yRot, zRot];
                            var oriMat = rotationToMatrix(ori);
                            var rotMat = rotationToMatrix(rotationVals);
                            var finalMat = multiplyMatrix3x3(oriMat, rotMat);
                            var applied = applyMatrixToOffset(finalMat, localOffsetX, localOffsetY, localOffsetZ);
                            var basePos = textLayer.transform.position.value;
                            var finalPos3 = [
                                basePos[0] + applied[0],
                                basePos[1] + applied[1],
                                (basePos.length > 2 ? basePos[2] : 0) + (applied[2] || 0),
                            ];
                            try {
                                if (!characterLayer.transform.position.dimensionsSeparated) {
                                    setPosition(characterLayer.transform.property(ADBE.Position), finalPos3);
                                }
                                else {
                                    setPosition(characterLayer.transform.property(ADBE.Position_0), finalPos3[0]);
                                    setPosition(characterLayer.transform.property(ADBE.Position_1), finalPos3[1]);
                                    if (characterLayer.transform.property(ADBE.Position_2)) {
                                        setPosition(characterLayer.transform.property(ADBE.Position_2), finalPos3[2]);
                                    }
                                }
                            }
                            catch (e) {
                                try {
                                    characterLayer.transform.position.setValue(finalPos3);
                                }
                                catch (e2) {
                                    void e2;
                                }
                            }
                        }
                    }
                    catch (posError) {
                        try {
                            characterLayer.transform.position.setValue(textLayer.transform.position.value);
                        }
                        catch (e2) {
                            void e2;
                        }
                    }
                    characterLayer.inPoint = layerInPoint;
                    characterLayer.outPoint = layerOutPoint;
                    if (onProgress) {
                        onProgress(baseProgress + Math.round((charIndex / Math.max(1, cleanText.length)) * span), 'Styling character ' + (charIndex + 1) + '/' + cleanText.length + '...');
                    }
                }
                onProgress === null || onProgress === void 0 ? void 0 : onProgress(86, 'Cleaning up...');
                try {
                    textLayer.enabled = false;
                }
                catch (e) {
                    void e;
                }
                for (var rem = 0; rem < allShapes.length; rem++) {
                    try {
                        allShapes[rem].remove();
                    }
                    catch (e) {
                        void e;
                    }
                }
                try {
                    for (var ss = 0; ss < comp.selectedLayers.length; ss++) {
                        comp.selectedLayers[ss].selected = false;
                    }
                }
                catch (e) {
                    void e;
                }
                for (var rr = 0; rr < resultLayers.length; rr++) {
                    try {
                        resultLayers[rr].selected = true;
                    }
                    catch (e) {
                        void e;
                    }
                }
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(99, 'Finalizing...');
            try {
                (_b = (_a = globalThis.$).sleep) === null || _b === void 0 ? void 0 : _b.call(_a, 150);
            }
            catch (e) {
                void e;
            }
            onProgress === null || onProgress === void 0 ? void 0 : onProgress(100, 'Completed!');
            try {
                (_d = (_c = globalThis.$).sleep) === null || _d === void 0 ? void 0 : _d.call(_c, 250);
            }
            catch (e) {
                void e;
            }
            app.endUndoGroup();
        }
        catch (err) {
            try {
                app.endUndoGroup();
            }
            catch (e) {
            }
            alert('Error: ' + ((err === null || err === void 0 ? void 0 : err.toString) ? err.toString() : err));
        }
    }

    // Baramoji_txt_win.jsx entry — text-layer decomposition with progress window.
    // Original: Baramoji_txt_win.jsx (Copyright 2024 Nisai, 2025 361do_sleep).
    (function BaramojiTxtWinEntry() {
        var mode = promptDuplicateMode();
        if (mode === null)
            return;
        var progress = makeProgressHelpers({ title: 'Text decomposition in progress' });
        try {
            runDecomposeTextToTextLayers({ onProgress: progress.update, duplicateMode: mode });
        }
        finally {
            progress.close();
        }
    })();

})();
